//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class aaa
    {
        public int aa { get; set; }
        public string nameaa { get; set; }
        public string addressaa { get; set; }
    }
}
