//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClsDirection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClsDirection()
        {
            this.ClsDirectionDepartments = new HashSet<ClsDirectionDepartment>();
            this.ClsInvestigationsBips = new HashSet<ClsInvestigationsBip>();
            this.ClsInvestigationsBipsDirections = new HashSet<ClsInvestigationsBipsDirection>();
            this.ClsPositions = new HashSet<ClsPosition>();
            this.Employees = new HashSet<Employee>();
            this.Employees1 = new HashSet<Employee>();
            this.Employees2 = new HashSet<Employee>();
            this.FlwAttendancesDays = new HashSet<FlwAttendancesDay>();
            this.FlwDepartmentsEmps = new HashSet<FlwDepartmentsEmp>();
            this.FlwOutsourceAttendances = new HashSet<FlwOutsourceAttendance>();
            this.FlwOutsourceAttendances1 = new HashSet<FlwOutsourceAttendance>();
            this.MlExits = new HashSet<MlExit>();
            this.FnPreBooks = new HashSet<FnPreBook>();
            this.FnPreBooks1 = new HashSet<FnPreBook>();
            this.FrAdvances = new HashSet<FrAdvance>();
            this.FrEvals = new HashSet<FrEval>();
            this.HrJobDescriptionRequests = new HashSet<HrJobDescriptionRequest>();
            this.HrSalaryPayRolls = new HashSet<HrSalaryPayRoll>();
            this.IntIntedabRequests = new HashSet<IntIntedabRequest>();
            this.IntIntedabRequests1 = new HashSet<IntIntedabRequest>();
            this.IntIntedabsDirectionsSettings = new HashSet<IntIntedabsDirectionsSetting>();
            this.LfIssDefs = new HashSet<LfIssDef>();
            this.LfMngNotes = new HashSet<LfMngNote>();
            this.LfPunishments = new HashSet<LfPunishment>();
            this.MgAppointements = new HashSet<MgAppointement>();
            this.MgAppointements1 = new HashSet<MgAppointement>();
            this.MLSuspends = new HashSet<MLSuspend>();
            this.Occupied_Vacancies = new HashSet<Occupied_Vacancies>();
            this.Projects = new HashSet<Project>();
            this.RcAddServices = new HashSet<RcAddService>();
            this.RcAddServices1 = new HashSet<RcAddService>();
            this.RcAllowances = new HashSet<RcAllowance>();
            this.RcAnnexations = new HashSet<RcAnnexation>();
            this.RcAnnexations1 = new HashSet<RcAnnexation>();
            this.RcAssignments = new HashSet<RcAssignment>();
            this.RcBnsRwdAlns = new HashSet<RcBnsRwdAln>();
            this.RcCommissionings = new HashSet<RcCommissioning>();
            this.RcCommissionings1 = new HashSet<RcCommissioning>();
            this.RcDelegates = new HashSet<RcDelegate>();
            this.RcDelegates1 = new HashSet<RcDelegate>();
            this.RcDelegates2 = new HashSet<RcDelegate>();
            this.RcJobExtends = new HashSet<RcJobExtend>();
            this.RcJobExtends1 = new HashSet<RcJobExtend>();
            this.RcJobExtends2 = new HashSet<RcJobExtend>();
            this.RcMedals = new HashSet<RcMedal>();
            this.RcPositions = new HashSet<RcPosition>();
            this.RcPositions1 = new HashSet<RcPosition>();
            this.RcPromotions = new HashSet<RcPromotion>();
            this.RcPromotions1 = new HashSet<RcPromotion>();
            this.RcRetirements = new HashSet<RcRetirement>();
            this.RcSeniors = new HashSet<RcSenior>();
            this.RcTransitions = new HashSet<RcTransition>();
            this.RcTransitions1 = new HashSet<RcTransition>();
            this.RcUpdates = new HashSet<RcUpdate>();
            this.RcUpdates1 = new HashSet<RcUpdate>();
            this.RgEmps = new HashSet<RgEmp>();
            this.RgEmps1 = new HashSet<RgEmp>();
            this.RgEmps2 = new HashSet<RgEmp>();
            this.StatisticsReportsNotes = new HashSet<StatisticsReportsNote>();
            this.SysBrPrmsDirections = new HashSet<SysBrPrmsDirection>();
            this.SysPagesDirections = new HashSet<SysPagesDirection>();
            this.SysReportsFooters = new HashSet<SysReportsFooter>();
            this.WfOfflineEmps = new HashSet<WfOfflineEmp>();
            this.WfOfflineEmps1 = new HashSet<WfOfflineEmp>();
            this.WfProcesses = new HashSet<WfProcess>();
            this.WfProcesses1 = new HashSet<WfProcess>();
            this.WfRequests = new HashSet<WfRequest>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string Details { get; set; }
        public string Code { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public bool IsFirstLevel { get; set; }
        public Nullable<int> FirstLevelID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> BankID { get; set; }
        public string AccountNum { get; set; }
        public Nullable<int> DirectionLevelID { get; set; }
        public int TypeID { get; set; }
        public string StatisticsCode { get; set; }
        public Nullable<int> ShameID { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string DMS_Num { get; set; }
        public Nullable<long> WebsiteID { get; set; }
    
        public virtual ClsBank ClsBank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClsDirectionDepartment> ClsDirectionDepartments { get; set; }
        public virtual ClsDirectionsLevel ClsDirectionsLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClsInvestigationsBip> ClsInvestigationsBips { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClsInvestigationsBipsDirection> ClsInvestigationsBipsDirections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClsPosition> ClsPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlwAttendancesDay> FlwAttendancesDays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlwDepartmentsEmp> FlwDepartmentsEmps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlwOutsourceAttendance> FlwOutsourceAttendances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlwOutsourceAttendance> FlwOutsourceAttendances1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MlExit> MlExits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnPreBook> FnPreBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnPreBook> FnPreBooks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrAdvance> FrAdvances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FrEval> FrEvals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrJobDescriptionRequest> HrJobDescriptionRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrSalaryPayRoll> HrSalaryPayRolls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntIntedabRequest> IntIntedabRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntIntedabRequest> IntIntedabRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntIntedabsDirectionsSetting> IntIntedabsDirectionsSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LfIssDef> LfIssDefs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LfMngNote> LfMngNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LfPunishment> LfPunishments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MgAppointement> MgAppointements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MgAppointement> MgAppointements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MLSuspend> MLSuspends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Occupied_Vacancies> Occupied_Vacancies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project> Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcAddService> RcAddServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcAddService> RcAddServices1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcAllowance> RcAllowances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcAnnexation> RcAnnexations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcAnnexation> RcAnnexations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcAssignment> RcAssignments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcBnsRwdAln> RcBnsRwdAlns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcCommissioning> RcCommissionings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcCommissioning> RcCommissionings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcDelegate> RcDelegates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcDelegate> RcDelegates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcDelegate> RcDelegates2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcJobExtend> RcJobExtends { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcJobExtend> RcJobExtends1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcJobExtend> RcJobExtends2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcMedal> RcMedals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcPosition> RcPositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcPosition> RcPositions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcPromotion> RcPromotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcPromotion> RcPromotions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcRetirement> RcRetirements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcSenior> RcSeniors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcTransition> RcTransitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcTransition> RcTransitions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcUpdate> RcUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcUpdate> RcUpdates1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RgEmp> RgEmps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RgEmp> RgEmps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RgEmp> RgEmps2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatisticsReportsNote> StatisticsReportsNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysBrPrmsDirection> SysBrPrmsDirections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysPagesDirection> SysPagesDirections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysReportsFooter> SysReportsFooters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfOfflineEmp> WfOfflineEmps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfOfflineEmp> WfOfflineEmps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfProcess> WfProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfProcess> WfProcesses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfRequest> WfRequests { get; set; }
    }
}
