//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClsDirectionDepartment
    {
        public int AutoID { get; set; }
        public int DepartmentsStructureID { get; set; }
        public int DirectionID { get; set; }
        public Nullable<int> GateID { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string DMS_Num { get; set; }
        public Nullable<long> WebsiteID { get; set; }
    
        public virtual ClsDepartmentsStructure ClsDepartmentsStructure { get; set; }
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual ClsGate ClsGate { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
