//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClsInvestigationsBip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClsInvestigationsBip()
        {
            this.ClsInvestigationsBipsDirections = new HashSet<ClsInvestigationsBipsDirection>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Details { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int DirectionID { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClsInvestigationsBipsDirection> ClsInvestigationsBipsDirections { get; set; }
    }
}
