//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClsInvestigationsBipsDirection
    {
        public int AutoID { get; set; }
        public int InvestigationsBipsID { get; set; }
        public int DirectionID { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual ClsInvestigationsBip ClsInvestigationsBip { get; set; }
    }
}
