//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoSupportRequest
    {
        public int AutoID { get; set; }
        public string AvailablePeriod { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ProductID { get; set; }
        public Nullable<System.DateTime> ValidPeriod { get; set; }
        public Nullable<bool> IsApproveM { get; set; }
        public Nullable<bool> IsApproveA { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> WebsiteID { get; set; }
    }
}
