//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoUserProfileReason
    {
        public long AutoID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<int> ReasonID { get; set; }
    
        public virtual CoReason CoReason { get; set; }
        public virtual CoUserProfile CoUserProfile { get; set; }
    }
}
