//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoUserParentsProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoUserParentsProfile()
        {
            this.CoSubParentFamilies = new HashSet<CoSubParentFamily>();
            this.CoSubParentsProfiles = new HashSet<CoSubParentsProfile>();
            this.CoSubParentUsers = new HashSet<CoSubParentUser>();
        }
    
        public long AutoID { get; set; }
        public string Name { get; set; }
        public string Relation { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string SID { get; set; }
        public string SIDLocation { get; set; }
        public Nullable<System.DateTime> SIDDatetime { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> SocialStatusID { get; set; }
        public Nullable<int> EducationalStatusID { get; set; }
        public string Qualification { get; set; }
        public string WorkPlace { get; set; }
        public string WorkPlaceLocation { get; set; }
        public string WorkPlacePhone { get; set; }
        public Nullable<bool> IsMotherLive { get; set; }
        public Nullable<bool> IsFatherLive { get; set; }
        public Nullable<System.DateTime> MotherDiedDate { get; set; }
        public Nullable<System.DateTime> FatherDiedDate { get; set; }
        public Nullable<int> CityID { get; set; }
        public string LivingLocation1 { get; set; }
        public string LivingLocation2 { get; set; }
        public string Mobile { get; set; }
        public string Name2 { get; set; }
        public string Mobile2 { get; set; }
        public Nullable<decimal> InSalary { get; set; }
        public Nullable<decimal> InSocialSecurity { get; set; }
        public Nullable<decimal> InSocialInsurance { get; set; }
        public Nullable<decimal> InRetirement { get; set; }
        public Nullable<decimal> InOther { get; set; }
        public Nullable<decimal> InTotal { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> Transport { get; set; }
        public Nullable<int> FamilySocialStatus { get; set; }
        public Nullable<int> HouseType { get; set; }
        public string HouseDescription { get; set; }
        public Nullable<int> WebsiteID { get; set; }
    
        public virtual CoEducationalStatu CoEducationalStatu { get; set; }
        public virtual CoSocialStatu CoSocialStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSubParentFamily> CoSubParentFamilies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSubParentsProfile> CoSubParentsProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoSubParentUser> CoSubParentUsers { get; set; }
    }
}
