//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemption
    {
        public int AutoID { get; set; }
        public int EmployeeID { get; set; }
        public int ExemptionReasonID { get; set; }
        public Nullable<System.DateTime> ExemptionDateFrom { get; set; }
        public Nullable<int> ExemptionTimeFrom { get; set; }
        public Nullable<System.DateTime> ExemptionDateTo { get; set; }
        public Nullable<int> ExemptionTimeTo { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ForigenID { get; set; }
        public Nullable<int> EmployeeLevelID { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
