//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlwEmployeesActivation
    {
        public int EmpID { get; set; }
        public Nullable<int> LastChangedBy { get; set; }
        public Nullable<System.DateTime> LastChangeDate { get; set; }
    }
}
