//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnBudget
    {
        public int AutoID { get; set; }
        public int RequestNum { get; set; }
        public int YearNum { get; set; }
        public string RequestName { get; set; }
        public int AccountID { get; set; }
        public int YearID { get; set; }
        public decimal StartAmount { get; set; }
        public string Details { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public int ProcessType { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<decimal> PreBooks { get; set; }
        public Nullable<decimal> EstTransfersDR { get; set; }
        public Nullable<decimal> EstTransfersCR { get; set; }
        public Nullable<decimal> EstTransfers { get; set; }
        public Nullable<decimal> ActTransfersDR { get; set; }
        public Nullable<decimal> ActTransfersCR { get; set; }
        public Nullable<decimal> ActTransfers { get; set; }
        public Nullable<decimal> FinalBooks { get; set; }
        public Nullable<decimal> EstPreBalance { get; set; }
        public Nullable<decimal> EstBalance { get; set; }
        public Nullable<decimal> ActBalance { get; set; }
        public bool IsFrozen { get; set; }
        public bool IsPreventN5 { get; set; }
        public bool IsPreventPreBook { get; set; }
        public bool IsPreventBook { get; set; }
    
        public virtual FnAccount FnAccount { get; set; }
        public virtual FnFinYear FnFinYear { get; set; }
        public virtual WfProcess WfProcess { get; set; }
    }
}
