//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnEstTransfer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FnEstTransfer()
        {
            this.FnBrEstTransfersAccounts = new HashSet<FnBrEstTransfersAccount>();
        }
    
        public int AutoID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int RequestNum { get; set; }
        public int YearNum { get; set; }
        public string RequestName { get; set; }
        public int YearID { get; set; }
        public int TypeID { get; set; }
        public bool IsOut { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnBrEstTransfersAccount> FnBrEstTransfersAccounts { get; set; }
    }
}
