//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FNExpenses_SMS
    {
        public int AutoId { get; set; }
        public Nullable<int> ExpenseId { get; set; }
        public Nullable<int> SmsId { get; set; }
    
        public virtual FNExpens FNExpens { get; set; }
        public virtual FNSm FNSm { get; set; }
    }
}
