//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnFinancialFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FnFinancialFile()
        {
            this.FnFinancialFilesSubs = new HashSet<FnFinancialFilesSub>();
        }
    
        public int AutoID { get; set; }
        public string Num { get; set; }
        public int Name { get; set; }
        public bool Type { get; set; }
        public string Place { get; set; }
        public int Band { get; set; }
        public int Direction { get; set; }
        public int Department { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnFinancialFilesSub> FnFinancialFilesSubs { get; set; }
    }
}
