//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnN5SubOrders
    {
        public int AutoID { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> OrderAdmin { get; set; }
        public Nullable<int> FinN5ID { get; set; }
    
        public virtual FnN5s FnN5s { get; set; }
    }
}
