//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnN5Files
    {
        public long AutoID { get; set; }
        public int N5ID { get; set; }
        public long FileID { get; set; }
    
        public virtual ClsFile ClsFile { get; set; }
        public virtual FnN5s FnN5s { get; set; }
    }
}
