//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnPaymentBankAccount
    {
        public int AutoID { get; set; }
        public string AccountCode { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public string AddressA { get; set; }
        public string AddressB { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string ContactPerson { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> BankID { get; set; }
        public string BankAccount { get; set; }
        public int CountryID { get; set; }
        public string Details { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
