//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnSubPaymentOrder
    {
        public long AutoID { get; set; }
        public int PaymentID { get; set; }
        public int AccountID { get; set; }
        public decimal Amount { get; set; }
        public string Details { get; set; }
        public int CurrencyID { get; set; }
        public Nullable<decimal> ForeignAmount { get; set; }
        public bool IsDebit { get; set; }
        public Nullable<bool> IsPrompt { get; set; }
    
        public virtual FnAccount FnAccount { get; set; }
        public virtual FnPaymentOrder FnPaymentOrder { get; set; }
    }
}
