//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrPrivilegesRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HrPrivilegesRequest()
        {
            this.HrPrivilegesRequestsProcesses = new HashSet<HrPrivilegesRequestsProcess>();
        }
    
        public long AutoID { get; set; }
        public int DirectionID { get; set; }
        public string YearID { get; set; }
        public string ModelCode { get; set; }
        public string RequestNum { get; set; }
        public string RequestName { get; set; }
        public int EmpID { get; set; }
        public int EmpSystemID { get; set; }
        public int EmpLevelID { get; set; }
        public int EmpDirectionID { get; set; }
        public int EmpDepartmentID { get; set; }
        public int SystemID { get; set; }
        public string PriviligesDetails { get; set; }
        public string Details { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public int ProcessType { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual HrSystem HrSystem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HrPrivilegesRequestsProcess> HrPrivilegesRequestsProcesses { get; set; }
    }
}
