//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrPrivilegesRequestsProcess
    {
        public long AutoID { get; set; }
        public long RequestID { get; set; }
        public int ProcessID { get; set; }
    
        public virtual HrPrivilegesRequest HrPrivilegesRequest { get; set; }
        public virtual HrProcess HrProcess { get; set; }
    }
}
