//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntIntedabRequestsLastInt
    {
        public long AutoID { get; set; }
        public int RequestID { get; set; }
        public System.DateTime StartDate { get; set; }
        public int DaysCount { get; set; }
        public bool IsExternal { get; set; }
    
        public virtual IntIntedabRequest IntIntedabRequest { get; set; }
    }
}
