//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LbSample
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LbSample()
        {
            this.LbAnalyses = new HashSet<LbAnalys>();
            this.LbJournals = new HashSet<LbJournal>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string Prefix { get; set; }
        public Nullable<int> PrefixNum { get; set; }
        public Nullable<int> SmplYear { get; set; }
        public Nullable<int> TrnsID { get; set; }
        public Nullable<int> IssueID { get; set; }
        public Nullable<int> SmplType { get; set; }
        public Nullable<decimal> DeductedQnt { get; set; }
        public Nullable<decimal> CurbedQnt { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> SuspectMaterial { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<System.DateTime> SafeDate { get; set; }
        public Nullable<int> SafeTime { get; set; }
        public Nullable<int> SafePerson { get; set; }
        public Nullable<int> SafePlace { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbAnalys> LbAnalyses { get; set; }
        public virtual LbClassification LbClassification { get; set; }
        public virtual LbIssue LbIssue { get; set; }
        public virtual LbIssue LbIssue1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbJournal> LbJournals { get; set; }
    }
}
