//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadersNegative
    {
        public int AutoID { get; set; }
        public int NominationID { get; set; }
        public string NegativeDetails { get; set; }
    
        public virtual LeadersNomination LeadersNomination { get; set; }
    }
}
