//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class LfIssEmp
    {
        public int AutoID { get; set; }
        public string OrderNum { get; set; }
        public string OrderAdmin { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string ExportNum { get; set; }
        public Nullable<System.DateTime> ExportDate { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> EmpLevel { get; set; }
        public Nullable<int> EmpSpNum { get; set; }
        public Nullable<int> EmpDirection1 { get; set; }
        public Nullable<int> EmpDirection2 { get; set; }
        public Nullable<int> EmpDirection3 { get; set; }
        public Nullable<int> CrimeID { get; set; }
        public string CrimeDetails { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
        public Nullable<bool> IsNotifyClosed { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<int> Result { get; set; }
        public string Details { get; set; }
        public Nullable<int> System { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
