//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mandate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mandate()
        {
            this.MandateGroups = new HashSet<MandateGroup>();
        }
    
        public int AutoID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsAuthoriz { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string LetterID { get; set; }
        public Nullable<int> MandateDateDay { get; set; }
        public Nullable<int> MandateDateMonth { get; set; }
        public Nullable<int> MandateDateYear { get; set; }
        public Nullable<int> MandateReciveDay { get; set; }
        public Nullable<int> MandateReciveMonth { get; set; }
        public Nullable<int> MandateReciveYear { get; set; }
        public string Title { get; set; }
        public Nullable<bool> IPAll { get; set; }
        public Nullable<bool> IPSome { get; set; }
        public Nullable<bool> DateAll { get; set; }
        public Nullable<bool> DateSome { get; set; }
        public Nullable<int> StartDay { get; set; }
        public Nullable<int> StartMonth { get; set; }
        public Nullable<int> StartYear { get; set; }
        public Nullable<int> EndDay { get; set; }
        public Nullable<int> EndMonth { get; set; }
        public Nullable<int> EndYear { get; set; }
        public Nullable<int> MandateType { get; set; }
        public string MandateDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MandateGroup> MandateGroups { get; set; }
    }
}
