//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MandateGroup
    {
        public int AutoId { get; set; }
        public Nullable<int> MandatId { get; set; }
        public string Type { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> ShiftId { get; set; }
    
        public virtual Mandate Mandate { get; set; }
    }
}
