//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MlBrRecordsVisitor
    {
        public long AutoID { get; set; }
        public int RecordID { get; set; }
        public int VisitorID { get; set; }
        public bool IsEntered { get; set; }
        public Nullable<int> EnterTime { get; set; }
        public string Details { get; set; }
        public string OutDetails { get; set; }
    
        public virtual MLVisitor MLVisitor { get; set; }
        public virtual MlVisitRecord MlVisitRecord { get; set; }
    }
}
