//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MlVisitRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MlVisitRecord()
        {
            this.MlBrRecordsVisitors = new HashSet<MlBrRecordsVisitor>();
        }
    
        public int AutoID { get; set; }
        public int EmpID { get; set; }
        public int RequestNum { get; set; }
        public int YearID { get; set; }
        public int DirectionID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public int LevelID { get; set; }
        public int GateID { get; set; }
        public string Details { get; set; }
        public System.DateTime VisitDate { get; set; }
        public Nullable<int> VisitTime { get; set; }
        public string OutDetails { get; set; }
        public int StatusID { get; set; }
        public int VisitorsCount { get; set; }
        public int EnteredCount { get; set; }
        public Nullable<int> RemainCount { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MlBrRecordsVisitor> MlBrRecordsVisitors { get; set; }
    }
}
