//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MpTicket
    {
        public long AutoID { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Subject { get; set; }
        public Nullable<int> State { get; set; }
        public string Details { get; set; }
        public Nullable<int> Eval { get; set; }
        public Nullable<int> FileID { get; set; }
        public string FilePath { get; set; }
        public Nullable<bool> IsReadAdmin { get; set; }
        public string IsReadUser { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
