//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPortalSection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyPortalSection()
        {
            this.MyPortalSectionCategories = new HashSet<MyPortalSectionCategory>();
            this.MyPortalSectionProducts = new HashSet<MyPortalSectionProduct>();
        }
    
        public int AutoID { get; set; }
        public Nullable<int> WebSiteID { get; set; }
        public string Name { get; set; }
        public Nullable<int> SectionType { get; set; }
        public Nullable<int> SectionElement { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> WebSiteSectionID { get; set; }
        public Nullable<int> ContentTemplate { get; set; }
        public Nullable<int> TemplateID { get; set; }
        public Nullable<bool> SecDisplayWay { get; set; }
        public Nullable<int> SecMovement { get; set; }
        public Nullable<bool> SecActive { get; set; }
        public Nullable<int> SecMainLocation { get; set; }
        public Nullable<int> SecSubLocation { get; set; }
        public Nullable<bool> SecDisplay { get; set; }
        public Nullable<bool> SecItemsOrders { get; set; }
        public Nullable<int> SecElementNumbers { get; set; }
        public Nullable<bool> SecForManager { get; set; }
        public Nullable<int> SecSectionOrders { get; set; }
        public Nullable<bool> SecContect { get; set; }
        public string SecGroup { get; set; }
        public string txtSecCSS { get; set; }
        public string SecDisplayCondition { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string DetailContent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyPortalSectionCategory> MyPortalSectionCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyPortalSectionProduct> MyPortalSectionProducts { get; set; }
    }
}
