//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPortalPage
    {
        public long PageID { get; set; }
        public string PageTitle { get; set; }
        public string PageContent { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<long> PageOrder { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string PageType { get; set; }
        public string PageKind { get; set; }
        public string PagePrim { get; set; }
    }
}
