//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPortalTemplate
    {
        public int AutoID { get; set; }
        public string Title { get; set; }
        public Nullable<int> DesignID { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string MHeader { get; set; }
        public string MFooter { get; set; }
        public string MSelected { get; set; }
        public string MCode { get; set; }
        public string SHeader { get; set; }
        public string SFooter { get; set; }
        public string SSelected { get; set; }
        public string SCode { get; set; }
        public string Optional1 { get; set; }
        public string Optional2 { get; set; }
        public string Optional3 { get; set; }
        public string Optional4 { get; set; }
        public Nullable<int> WebSiteID { get; set; }
    
        public virtual MyPortalDesign MyPortalDesign { get; set; }
    }
}
