//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPortalEmail
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public int WebSiteID { get; set; }
        public string HeaderLink1 { get; set; }
        public string HeaderLink2 { get; set; }
        public string HeaderLink3 { get; set; }
        public string HeaderLink4 { get; set; }
        public string HeaderLinkText1 { get; set; }
        public string HeaderLinkText2 { get; set; }
        public string HeaderLinkText3 { get; set; }
        public string HeaderLinkText4 { get; set; }
        public string FooterLink1 { get; set; }
        public string FooterLink2 { get; set; }
        public string FooterLink3 { get; set; }
        public string FooterLink4 { get; set; }
        public string FooterLinkText1 { get; set; }
        public string FooterLinkText2 { get; set; }
        public string FooterLinkText3 { get; set; }
        public string FooterLinkText4 { get; set; }
        public string Template { get; set; }
        public Nullable<long> ImageLogo { get; set; }
        public string Copyright { get; set; }
        public string Address { get; set; }
        public string FaceBook { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
    }
}
