//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPortalElementsImage
    {
        public long AutoID { get; set; }
        public Nullable<long> ElementImage { get; set; }
        public Nullable<int> ElementID { get; set; }
    
        public virtual MyPortalElement MyPortalElement { get; set; }
    }
}
