//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPortalSectionProduct
    {
        public int AutoID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<long> ProductID { get; set; }
    
        public virtual MyPortalSection MyPortalSection { get; set; }
        public virtual ScPackage ScPackage { get; set; }
    }
}
