//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class NfType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NfType()
        {
            this.NfNotifications = new HashSet<NfNotification>();
            this.SysPages = new HashSet<SysPage>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public int PageID { get; set; }
        public Nullable<int> PageID2 { get; set; }
        public Nullable<int> PageDetails { get; set; }
        public string DefaultMessage { get; set; }
        public int OrderBy { get; set; }
        public string Details { get; set; }
        public Nullable<long> IconID { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Code { get; set; }
    
        public virtual ClsFile ClsFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NfNotification> NfNotifications { get; set; }
        public virtual SysPage SysPage { get; set; }
        public virtual SysPage SysPage1 { get; set; }
        public virtual SysPage SysPage2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysPage> SysPages { get; set; }
    }
}
