//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class NICIssue
    {
        public long AutoID { get; set; }
        public string IssueName { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public Nullable<int> RecordPlaceDirectionID { get; set; }
        public string hjRecordDate { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string zPersonsCount { get; set; }
        public Nullable<int> PersonsCount { get; set; }
        public string RecordNum { get; set; }
        public string IssueStatus { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public string RecordPlace { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
