//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class OverTimeCalc
    {
        public int AutoID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<decimal> EmpSalary { get; set; }
        public string EmpDegree { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<decimal> DegreeTransAllowance { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsWeekEnd { get; set; }
        public Nullable<int> WorkDaysCount { get; set; }
        public Nullable<int> WeekEndDaysCount { get; set; }
        public Nullable<decimal> RateWorkDays { get; set; }
        public Nullable<decimal> RateWeekEndDays { get; set; }
        public Nullable<int> MaxType { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public Nullable<decimal> TransAllowanceAmount { get; set; }
        public Nullable<decimal> DaysAmountBeforeMaxLimit { get; set; }
        public Nullable<decimal> DaysAmountAfterMaxLimit { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual OverTimeOrder OverTimeOrder { get; set; }
    }
}
