//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsAchievment
    {
        public int AutoID { get; set; }
        public int ProjectID { get; set; }
        public decimal AchievmentAmount { get; set; }
        public System.DateTime AchievmentDate { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
