//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcEmpsCard
    {
        public int AutoID { get; set; }
        public int EmpID { get; set; }
        public int EmpSystemID { get; set; }
        public int EmpLevelID { get; set; }
        public bool IsRetired { get; set; }
        public string PositionName { get; set; }
        public string LevelName { get; set; }
        public string ManagerName { get; set; }
        public System.DateTime StartDate { get; set; }
        public long ImageID { get; set; }
        public bool IsPrinted { get; set; }
        public Nullable<int> PrintEmpID { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ClsFile ClsFile { get; set; }
        public virtual ClsLevel ClsLevel { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
