//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcMedal
    {
        public int AutoID { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderAdmin { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> EmpDirection { get; set; }
        public Nullable<int> EmpDirection1 { get; set; }
        public Nullable<int> EmpDirection2 { get; set; }
        public Nullable<int> EmpDirection3 { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> MedalID { get; set; }
        public string Degree { get; set; }
        public Nullable<bool> IsMinistryApproved { get; set; }
        public string Reason { get; set; }
        public string Details { get; set; }
        public int SystemID { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual RcClassification RcClassification { get; set; }
    }
}
