//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcPosition
    {
        public int AutoID { get; set; }
        public int EmpID { get; set; }
        public string EmpPosition { get; set; }
        public Nullable<System.DateTime> EmpPositionDate { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderAdmin { get; set; }
        public Nullable<bool> IsPosition { get; set; }
        public Nullable<bool> EmpIsOn { get; set; }
        public Nullable<int> EmpDirection { get; set; }
        public Nullable<int> EmpDirection1 { get; set; }
        public Nullable<int> EmpDirection2 { get; set; }
        public Nullable<int> EmpDirection3 { get; set; }
        public Nullable<bool> IsLetter { get; set; }
        public string Position { get; set; }
        public Nullable<bool> IsOnDrugSector { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public Nullable<int> Direction1ID { get; set; }
        public Nullable<int> Direction2ID { get; set; }
        public Nullable<int> Direction3ID { get; set; }
        public Nullable<int> Dept1ID { get; set; }
        public Nullable<int> Dept2ID { get; set; }
        public Nullable<int> Dept3ID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string DirectionName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Details { get; set; }
        public int System { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual ClsDirection ClsDirection1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
