//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcQlfsType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RcQlfsType()
        {
            this.ClsLevels = new HashSet<ClsLevel>();
            this.Employees = new HashSet<Employee>();
            this.PrEmpPoints = new HashSet<PrEmpPoint>();
            this.RcQualifications = new HashSet<RcQualification>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PromotionPoints { get; set; }
        public Nullable<int> ReqDays { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> SpcID { get; set; }
        public string Details { get; set; }
        public int System { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<long> WebsiteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClsLevel> ClsLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrEmpPoint> PrEmpPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcQualification> RcQualifications { get; set; }
    }
}
