//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcTransition
    {
        public int AutoID { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderAdmin { get; set; }
        public Nullable<bool> IsOnFrom { get; set; }
        public bool IsOnTo { get; set; }
        public Nullable<int> DirectionFrom { get; set; }
        public Nullable<int> DirectionTo { get; set; }
        public Nullable<int> DepartmentFrom { get; set; }
        public Nullable<int> DepartmentTo { get; set; }
        public Nullable<int> Direction1From { get; set; }
        public Nullable<int> Direction1To { get; set; }
        public Nullable<int> Direction2From { get; set; }
        public Nullable<int> Direction2To { get; set; }
        public Nullable<int> Direction3From { get; set; }
        public Nullable<int> Direction3To { get; set; }
        public Nullable<int> Dept1From { get; set; }
        public Nullable<int> Dept1To { get; set; }
        public Nullable<int> Dept2From { get; set; }
        public Nullable<int> Dept2To { get; set; }
        public Nullable<int> Dept3From { get; set; }
        public Nullable<int> Dept3To { get; set; }
        public Nullable<int> SpNumFrom { get; set; }
        public Nullable<int> SpNumTo { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Position { get; set; }
        public string Reason { get; set; }
        public string Details { get; set; }
        public int System { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual ClsDirection ClsDirection1 { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual RcSpecialNumber RcSpecialNumber { get; set; }
        public virtual RcSpecialNumber RcSpecialNumber1 { get; set; }
    }
}
