//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceivingsDetailsMember
    {
        public long AutoID { get; set; }
        public int ReceivingsID { get; set; }
        public int EmpID { get; set; }
        public string ReceiptsName { get; set; }
        public string ReceiptsLevelName { get; set; }
        public Nullable<System.DateTime> ReceiptsDate { get; set; }
        public Nullable<int> ReceiptsTime { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Details { get; set; }
        public Nullable<int> ReplacedId { get; set; }
        public Nullable<int> ReasonID { get; set; }
    
        public virtual Receiving Receiving { get; set; }
    }
}
