//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScClient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScClient()
        {
            this.ScMarkterPromos = new HashSet<ScMarkterPromo>();
            this.ScMarkterPromos1 = new HashSet<ScMarkterPromo>();
            this.ScSubClientMarkters = new HashSet<ScSubClientMarkter>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public int ClientType { get; set; }
        public string Code { get; set; }
        public Nullable<int> Manager { get; set; }
        public string Type { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string mailbox { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> City { get; set; }
        public string Fax { get; set; }
        public string Details { get; set; }
        public string AccountNo { get; set; }
        public string BankName { get; set; }
        public string BankUserName { get; set; }
        public string RelativeMobile { get; set; }
        public Nullable<long> ImageID { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<decimal> Openingbalance { get; set; }
        public Nullable<decimal> Currentbalance { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public Nullable<decimal> CreditLimit { get; set; }
        public string CreditTerm { get; set; }
        public string Currency { get; set; }
        public string mailboxCode { get; set; }
        public Nullable<bool> DealTypeNow { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> MarketerID { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<int> AccountantNum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScMarkterPromo> ScMarkterPromos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScMarkterPromo> ScMarkterPromos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubClientMarkter> ScSubClientMarkters { get; set; }
    }
}
