//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScPaymentSetting
    {
        public int AutoID { get; set; }
        public string SecureHashCode { get; set; }
        public string Merchant { get; set; }
        public string MerchTxtRef { get; set; }
        public string AccessCode { get; set; }
        public string Currency { get; set; }
        public Nullable<int> ProcessorID { get; set; }
        public string Language { get; set; }
        public Nullable<int> ExtraParameter1 { get; set; }
        public Nullable<int> ExtraParameter2 { get; set; }
        public Nullable<int> ExtraParameter3 { get; set; }
        public string MerchantModuleSessionID { get; set; }
        public string OlpIdAlias { get; set; }
    }
}
