//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScPackagesAttribute
    {
        public long AutoID { get; set; }
        public Nullable<long> PackageID { get; set; }
        public Nullable<int> AttributeID { get; set; }
    
        public virtual ScAttribute ScAttribute { get; set; }
        public virtual ScPackage ScPackage { get; set; }
    }
}
