//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScProduct()
        {
            this.ScProductsCategories = new HashSet<ScProductsCategory>();
            this.ScProductsImages = new HashSet<ScProductsImage>();
            this.ScRelatedProducts = new HashSet<ScRelatedProduct>();
            this.ScRelatedProducts1 = new HashSet<ScRelatedProduct>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Details { get; set; }
        public Nullable<long> ImageID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<bool> ProductQtyType { get; set; }
        public Nullable<int> TaxType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScProductsCategory> ScProductsCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScProductsImage> ScProductsImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScRelatedProduct> ScRelatedProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScRelatedProduct> ScRelatedProducts1 { get; set; }
    }
}
