//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScPurchasesRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScPurchasesRequest()
        {
            this.ScSubPurchaseRequests = new HashSet<ScSubPurchaseRequest>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public int RequestsStatus { get; set; }
        public System.DateTime RequestsDate { get; set; }
        public int TimeLengh { get; set; }
        public int TimeType { get; set; }
        public string Details { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public int ProcessType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> WebsiteID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubPurchaseRequest> ScSubPurchaseRequests { get; set; }
    }
}
