//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSubSalesRequest
    {
        public int AutoID { get; set; }
        public Nullable<long> PackageID { get; set; }
        public Nullable<int> SalesRequestID { get; set; }
        public Nullable<int> Qnt { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual ScPackage ScPackage { get; set; }
        public virtual ScSalesRequest ScSalesRequest { get; set; }
    }
}
