//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SlCompany()
        {
            this.SlLicenses = new HashSet<SlLicens>();
            this.SlDeductions = new HashSet<SlDeduction>();
            this.SlInternals = new HashSet<SlInternal>();
            this.SlInternals1 = new HashSet<SlInternal>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string BuildingNum { get; set; }
        public string Street { get; set; }
        public string Neighborhood { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Mobile { get; set; }
        public string ECoordinates { get; set; }
        public string NCoordinates { get; set; }
        public Nullable<long> ImgCoordinateID { get; set; }
        public string ImgCoordinates { get; set; }
        public string AddressB { get; set; }
        public string PostBox { get; set; }
        public string CRNum { get; set; }
        public Nullable<System.DateTime> CRDate { get; set; }
        public string StockPerson { get; set; }
        public string StockPersonSID { get; set; }
        public string StockPersonMobile { get; set; }
        public string StockPersonB { get; set; }
        public string StockPersonC { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<bool> IsActiveIn { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ClsFile ClsFile { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlLicens> SlLicenses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlDeduction> SlDeductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlInternal> SlInternals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlInternal> SlInternals1 { get; set; }
    }
}
