//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlDeduction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SlDeduction()
        {
            this.SlDeductsMaterials = new HashSet<SlDeductsMaterial>();
        }
    
        public int AutoID { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> PortID { get; set; }
        public Nullable<System.DateTime> PortDate { get; set; }
        public string ExporterName { get; set; }
        public Nullable<int> ExporterCountry { get; set; }
        public string ExporterAddress { get; set; }
        public string ProducerName { get; set; }
        public Nullable<int> ProducerCountry { get; set; }
        public string producerAddress { get; set; }
        public Nullable<int> ImporterID { get; set; }
        public Nullable<int> LicenseID { get; set; }
        public Nullable<bool> IsReleased { get; set; }
        public string ReleaseNum { get; set; }
        public Nullable<System.DateTime> ReleaseStartDate { get; set; }
        public Nullable<System.DateTime> ReleaseEndDate { get; set; }
        public string InvoiceNum { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string BLNum { get; set; }
        public Nullable<System.DateTime> BLDate { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ClsPlace ClsPlace { get; set; }
        public virtual SlCompany SlCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlDeductsMaterial> SlDeductsMaterials { get; set; }
    }
}
