//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlInternalMaterial
    {
        public int AutoID { get; set; }
        public int InternalID { get; set; }
        public int MaterialID { get; set; }
        public decimal MaterialQnt { get; set; }
    
        public virtual SlInternal SlInternal { get; set; }
        public virtual SlMaterial SlMaterial { get; set; }
    }
}
