//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SlMaterial()
        {
            this.SlDeductsMaterials = new HashSet<SlDeductsMaterial>();
            this.SlInternalMaterials = new HashSet<SlInternalMaterial>();
            this.SlLicensesMaterials = new HashSet<SlLicensesMaterial>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public string HsNum { get; set; }
        public string CASNum { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> TableID { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlDeductsMaterial> SlDeductsMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlInternalMaterial> SlInternalMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SlLicensesMaterial> SlLicensesMaterials { get; set; }
    }
}
