//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatisticsIssue
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StatisticsIssue()
        {
            this.ClsIssuesFiles = new HashSet<ClsIssuesFile>();
        }
    
        public int AutoID { get; set; }
        public int DirectionID { get; set; }
        public string IssueNum { get; set; }
        public string DirectionNum { get; set; }
        public string YearNum { get; set; }
        public string IssueName { get; set; }
        public System.DateTime IssueDate { get; set; }
        public Nullable<int> IssueTime { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> TransportWayID { get; set; }
        public Nullable<int> CriminalMethodID { get; set; }
        public Nullable<bool> ArrestDirectionIsOn { get; set; }
        public Nullable<int> ArrestDirectionID { get; set; }
        public Nullable<bool> InfoSourceDirectionIsOn { get; set; }
        public Nullable<int> InfoSourceDirectionID { get; set; }
        public Nullable<bool> ArrestPersonsDirectionIsOn { get; set; }
        public Nullable<int> ArrestPersonsDirectionID { get; set; }
        public Nullable<bool> ArrestAddressIsOn { get; set; }
        public Nullable<int> ArrestAddressCountry { get; set; }
        public Nullable<long> ArrestAddressID { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string MaiNSaveFormNum { get; set; }
        public string SubSaveFormNum { get; set; }
        public string ArchiveDetails { get; set; }
        public int EnteranceTypeID { get; set; }
        public string IssueBrief { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClsIssuesFile> ClsIssuesFiles { get; set; }
    }
}
