//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyFuelsOut
    {
        public int AutoID { get; set; }
        public int DirectionID { get; set; }
        public int OutDate { get; set; }
        public int CarID { get; set; }
        public int EmpID { get; set; }
        public int EmpLevel { get; set; }
        public int EmpDirection { get; set; }
        public string EmpDepartment { get; set; }
        public int Cylinder { get; set; }
        public int EstimatedAmount { get; set; }
        public int ReceivedAmount { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
