//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysMsgFile
    {
        public long AutoID { get; set; }
        public Nullable<long> MsgID { get; set; }
        public Nullable<long> FileID { get; set; }
    
        public virtual ClsFile ClsFile { get; set; }
        public virtual SysMsg SysMsg { get; set; }
    }
}
