//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysPgsPrm
    {
        public int AutoID { get; set; }
        public int PageID { get; set; }
        public int PrmID { get; set; }
        public string PrmField { get; set; }
    
        public virtual SysPage SysPage { get; set; }
    }
}
