//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysPages_1
    {
        public int AutoID { get; set; }
        public string PageLink { get; set; }
        public string ArabicName { get; set; }
        public Nullable<int> TableID { get; set; }
        public string Details { get; set; }
        public int Position { get; set; }
        public Nullable<int> Parent { get; set; }
        public Nullable<int> NotifyTypeID { get; set; }
        public int OrderBy { get; set; }
        public bool IsCustomPrms { get; set; }
        public Nullable<bool> IsForAll { get; set; }
        public Nullable<bool> IsForEmps { get; set; }
        public Nullable<bool> IsForClasses { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<bool> IsForLevels { get; set; }
        public Nullable<bool> IsForGroups { get; set; }
        public Nullable<bool> IsForSystems { get; set; }
        public Nullable<bool> IsForDirections { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public Nullable<bool> IsForDepartments { get; set; }
        public Nullable<bool> IsCommonPage { get; set; }
        public Nullable<bool> IsSubPrm { get; set; }
        public Nullable<bool> IsAutoSubPrms { get; set; }
        public Nullable<bool> IsOpenPerms { get; set; }
        public long IconID { get; set; }
        public Nullable<bool> IsHasModel { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public int MainSystemID { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string TableName { get; set; }
    }
}
