//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysScreen
    {
        public int AutoID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<bool> IsFv { get; set; }
        public Nullable<int> CacheCount { get; set; }
    
        public virtual SysPage SysPage { get; set; }
    }
}
