//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDashboardIssues5_3_Subs
    {
        public string DirectionName { get; set; }
        public string DirectionSubName { get; set; }
        public Nullable<int> IssuesCounts { get; set; }
        public string HjriIssueDate { get; set; }
    }
}
