//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWDashboard_HR4_Subs
    {
        public string FirstLevelDirectionName { get; set; }
        public string DirectionName { get; set; }
        public Nullable<int> Count { get; set; }
        public int Under25Count { get; set; }
        public int Between25and35Count { get; set; }
        public int Between35and45Count { get; set; }
        public int GreaterThan45Count { get; set; }
    }
}
