//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDashBoardTraining_3
    {
        public string CourseType { get; set; }
        public string Location { get; set; }
        public string HjriStartDate { get; set; }
        public Nullable<int> DurationDays { get; set; }
        public string EmpSystem { get; set; }
        public Nullable<int> CoursesCount { get; set; }
    }
}
