//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDashBoardMadarReport
    {
        public int DirectionID { get; set; }
        public string DirectionName { get; set; }
        public string HjriReportDate { get; set; }
        public int IsHasActions { get; set; }
        public int IsHasEdits { get; set; }
        public int IsHasTransfers { get; set; }
        public Nullable<int> ReportsCount { get; set; }
    }
}
