//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDashBoardSuspects_1
    {
        public string SuspectNum { get; set; }
        public string DirectionName { get; set; }
        public Nullable<int> ObservationPeriod { get; set; }
        public Nullable<System.DateTime> ObservationStartDate { get; set; }
        public Nullable<System.DateTime> ObservationEndDate { get; set; }
        public string IsUnderObservation { get; set; }
    }
}
