//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwFlwAttendeesDetail
    {
        public long AttendanceEmpAutoID { get; set; }
        public System.DateTime AttendanceDate { get; set; }
        public string FullName { get; set; }
        public int EmployeeID { get; set; }
        public string SID { get; set; }
        public int StatusID { get; set; }
    }
}
