//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwFnJournalsSub
    {
        public int DocID { get; set; }
        public int YearID { get; set; }
        public int MonthID { get; set; }
        public int IsJournal { get; set; }
        public int DocNum { get; set; }
        public System.DateTime JournalDate { get; set; }
        public int AccountID { get; set; }
        public int AccountJournalID { get; set; }
        public bool IsDebit { get; set; }
        public Nullable<decimal> Amount { get; set; }
    }
}
