//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwFnMonthlyBalance_5
    {
        public int AccountID { get; set; }
        public string Num { get; set; }
        public string Name { get; set; }
        public int YearID { get; set; }
        public int MonthID { get; set; }
        public decimal CurrentDebit { get; set; }
        public decimal CurrentCredit { get; set; }
    }
}
