//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwGDNCMadarDocumentsStore
    {
        public long AutoID { get; set; }
        public int CreatedBy { get; set; }
        public int PageID { get; set; }
        public System.Guid stream_id { get; set; }
        public byte[] file_stream { get; set; }
        public string file_type { get; set; }
        public string IconBase64String { get; set; }
        public bool IsImage { get; set; }
        public string FullFileName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
