//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwInvN10s
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductNum { get; set; }
        public Nullable<int> StoreSubID { get; set; }
        public string StoreName { get; set; }
        public int StoreID { get; set; }
        public Nullable<decimal> EstimatedQnt { get; set; }
        public Nullable<decimal> ActualQnt { get; set; }
    }
}
