//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwInvN4Details
    {
        public Nullable<decimal> Balance { get; set; }
        public decimal PrvIns { get; set; }
        public decimal PrvOuts { get; set; }
        public Nullable<long> VID { get; set; }
        public int IsIn { get; set; }
        public long AutoID { get; set; }
        public int ReceiptID { get; set; }
        public System.DateTime ReceiptDate { get; set; }
        public Nullable<int> SpcNum { get; set; }
        public int YearID { get; set; }
        public string GovNum { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> StoreID { get; set; }
        public decimal InQnt { get; set; }
        public string InDirection { get; set; }
        public decimal OutQnt { get; set; }
        public string OutDirection { get; set; }
        public int ModelID { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
