//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwInvN16Directions
    {
        public Nullable<int> StoreSubID { get; set; }
        public Nullable<int> DirectionTo { get; set; }
        public string DirectionName { get; set; }
        public int ProductID { get; set; }
        public Nullable<decimal> EstQnt { get; set; }
        public Nullable<decimal> ActQnt { get; set; }
    }
}
