//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwMgBuffet
    {
        public int DirectionID { get; set; }
        public int PositionID { get; set; }
        public int BuffetID { get; set; }
        public string BuffetName { get; set; }
        public Nullable<int> BuffetOrder { get; set; }
        public int OrderID { get; set; }
        public int OrderNum { get; set; }
        public int BuffetCount { get; set; }
    }
}
