//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwRawabitPersonsReport
    {
        public long PersonAutoID { get; set; }
        public string FullName { get; set; }
        public string IDNum { get; set; }
        public string Nationality { get; set; }
        public long IssueAutoID { get; set; }
        public string ReportName { get; set; }
        public System.DateTime ReportDate { get; set; }
        public string Gender { get; set; }
    }
}
