//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwRawabit_1
    {
        public long PersonAutoID { get; set; }
        public string FullName { get; set; }
        public string SIDNum { get; set; }
        public string Nationality { get; set; }
        public int IssueAutoID { get; set; }
        public string IssueName { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string Gender { get; set; }
        public string TypeName { get; set; }
    }
}
