//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwWfRelatedRequest
    {
        public int DocID { get; set; }
        public int EmpID { get; set; }
        public int ModelID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public string ModelCode { get; set; }
        public int IsAssigned { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    }
}
