//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WfModel()
        {
            this.SysPages = new HashSet<SysPage>();
            this.WfDocsProcesses = new HashSet<WfDocsProcess>();
            this.WfRequests = new HashSet<WfRequest>();
            this.WfModelsClasses = new HashSet<WfModelsClass>();
            this.WfModelsDepartments = new HashSet<WfModelsDepartment>();
            this.WfModelsDirections = new HashSet<WfModelsDirection>();
            this.WfModelsEmps = new HashSet<WfModelsEmp>();
            this.WfModelsGroups = new HashSet<WfModelsGroup>();
            this.WfModelsLevels = new HashSet<WfModelsLevel>();
            this.WfModelsSystems = new HashSet<WfModelsSystem>();
            this.WfProcesses = new HashSet<WfProcess>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Details { get; set; }
        public bool IsHasProcesses { get; set; }
        public bool IsService { get; set; }
        public Nullable<bool> IsForAll { get; set; }
        public Nullable<bool> IsForEmps { get; set; }
        public Nullable<bool> IsForClasses { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<bool> IsForLevels { get; set; }
        public Nullable<bool> IsForGroups { get; set; }
        public Nullable<bool> IsForSystems { get; set; }
        public Nullable<bool> IsForDirections { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public Nullable<bool> IsForDepartments { get; set; }
        public long IconID { get; set; }
        public int SystemID { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Code { get; set; }
        public Nullable<int> PageID { get; set; }
    
        public virtual ClsFile ClsFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysPage> SysPages { get; set; }
        public virtual SysPage SysPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfDocsProcess> WfDocsProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfRequest> WfRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfModelsClass> WfModelsClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfModelsDepartment> WfModelsDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfModelsDirection> WfModelsDirections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfModelsEmp> WfModelsEmps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfModelsGroup> WfModelsGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfModelsLevel> WfModelsLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfModelsSystem> WfModelsSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WfProcess> WfProcesses { get; set; }
    }
}
