//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfProcessGroup
    {
        public int AutoID { get; set; }
        public int ProcessID { get; set; }
        public int GroupID { get; set; }
    
        public virtual SysGroup SysGroup { get; set; }
        public virtual WfProcess WfProcess { get; set; }
    }
}
