//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CgDevicesInfo
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string PosVersion { get; set; }
        public string MacAddress { get; set; }
        public string WindowOperatingSystem { get; set; }
        public string WindowNetFrameworkVersion { get; set; }
        public string WindowNetFrameworkVersion2 { get; set; }
        public string WindowProcessor { get; set; }
        public string WindowRam { get; set; }
        public string WindowLanIp { get; set; }
        public string WindowsModel { get; set; }
        public string SystemProcessors { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public string Details { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<long> WebID { get; set; }
        public Nullable<int> SubscriptionID { get; set; }
    }
}
