//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CgMngDevice
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string MacID { get; set; }
        public Nullable<int> SiteID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> DeviceTypeID { get; set; }
        public Nullable<int> DeviceModelID { get; set; }
        public Nullable<int> OperationSystemID { get; set; }
        public Nullable<int> RamID { get; set; }
        public Nullable<int> ProcessorID { get; set; }
        public Nullable<int> SysTypeID { get; set; }
        public string Details { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public long WebsiteID { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string NationalAddress { get; set; }
    
        public virtual ScInventory ScInventory { get; set; }
        public virtual MyPortalWebsite MyPortalWebsite { get; set; }
    }
}
