//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClsAllowanceType
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Amount { get; set; }
        public Nullable<bool> IsSalaryRelated { get; set; }
        public Nullable<int> System { get; set; }
        public string Details { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> ID { get; set; }
        public string AllowanceName { get; set; }
        public string Description { get; set; }
        public Nullable<int> ValueType { get; set; }
        public string AllowanceValue { get; set; }
        public Nullable<bool> IsGivenWithSalary { get; set; }
    }
}
