//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClsArchiveFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClsArchiveFile()
        {
            this.LfIssuesFiles = new HashSet<LfIssuesFile>();
            this.RcEmpsDocumentations = new HashSet<RcEmpsDocumentation>();
        }
    
        public long AutoID { get; set; }
        public Nullable<System.Guid> DocumentStreamID { get; set; }
        public string Name { get; set; }
        public int PageID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Details { get; set; }
        public Nullable<int> PagesCount { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LfIssuesFile> LfIssuesFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RcEmpsDocumentation> RcEmpsDocumentations { get; set; }
    }
}
