//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClsDepartmentsStructure
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClsDepartmentsStructure()
        {
            this.ClsDepartmentsStructures1 = new HashSet<ClsDepartmentsStructure>();
            this.ClsDirectionDepartments = new HashSet<ClsDirectionDepartment>();
            this.Employees = new HashSet<Employee>();
            this.Employees1 = new HashSet<Employee>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Details { get; set; }
        public Nullable<int> SampleDirectionID { get; set; }
        public Nullable<int> DirectionLevelID { get; set; }
        public bool IsFirstLevel { get; set; }
        public Nullable<int> FirstLevelID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<int> DirectionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClsDepartmentsStructure> ClsDepartmentsStructures1 { get; set; }
        public virtual ClsDepartmentsStructure ClsDepartmentsStructure1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClsDirectionDepartment> ClsDirectionDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees1 { get; set; }
    }
}
