//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeUsersOrder
    {
        public long AutoID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> SalesInvoiceID { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual FeUser FeUser { get; set; }
        public virtual ScSalesInvoice ScSalesInvoice { get; set; }
    }
}
