//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeUsersRating
    {
        public long AutoID { get; set; }
        public int UserID { get; set; }
        public long PackageID { get; set; }
        public decimal RateNo { get; set; }
        public System.DateTime RateDate { get; set; }
        public string Comment { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ScPackage ScPackage { get; set; }
    }
}
