//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnAccount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FnAccount()
        {
            this.FnBrEstTransfersAccounts = new HashSet<FnBrEstTransfersAccount>();
            this.FnBrTransfersAccounts = new HashSet<FnBrTransfersAccount>();
            this.FnBudgets = new HashSet<FnBudget>();
            this.FnPreBooks = new HashSet<FnPreBook>();
            this.FnSubBooks = new HashSet<FnSubBook>();
            this.FnSubJournals = new HashSet<FnSubJournal>();
            this.FnSubN5s = new HashSet<FnSubN5s>();
            this.FnSubPaymentOrders = new HashSet<FnSubPaymentOrder>();
            this.FnSubSettlements = new HashSet<FnSubSettlement>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string Num { get; set; }
        public Nullable<int> JournalID { get; set; }
        public Nullable<bool> IsDebit { get; set; }
        public Nullable<decimal> StartBalance { get; set; }
        public Nullable<bool> IsDebitBalance { get; set; }
        public bool IsN5Prompt { get; set; }
        public string Details { get; set; }
        public int OrderBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> EconomicNum { get; set; }
        public Nullable<int> RelParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnBrEstTransfersAccount> FnBrEstTransfersAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnBrTransfersAccount> FnBrTransfersAccounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnBudget> FnBudgets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnPreBook> FnPreBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnSubBook> FnSubBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnSubJournal> FnSubJournals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnSubN5s> FnSubN5s { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnSubPaymentOrder> FnSubPaymentOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnSubSettlement> FnSubSettlements { get; set; }
        public virtual FnParentsAccount FnParentsAccount { get; set; }
    }
}
