//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnBrTransfersAccount
    {
        public long AutoID { get; set; }
        public int TransferID { get; set; }
        public int AccountID { get; set; }
        public bool IsDebit { get; set; }
        public decimal Amount { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> YEAR_CODE { get; set; }
        public Nullable<decimal> TRANSFER_NUMBER { get; set; }
        public string ACCOUNT_CODE { get; set; }
        public Nullable<decimal> BUD_INC_TYPE { get; set; }
        public Nullable<decimal> FROM_AMOUNT { get; set; }
        public Nullable<decimal> TO_AMOUNT { get; set; }
    
        public virtual FnAccount FnAccount { get; set; }
        public virtual FnTransfer FnTransfer { get; set; }
    }
}
