//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnFinancialFilesSub
    {
        public long AutoID { get; set; }
        public int FnFinancialFilesID { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> BankName { get; set; }
        public string BankAccount { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string CivilRegistry { get; set; }
        public string RightOwnerName { get; set; }
        public string RightOwnerNumber { get; set; }
        public string Details { get; set; }
    
        public virtual FnFinancialFile FnFinancialFile { get; set; }
    }
}
