//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnJournal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FnJournal()
        {
            this.FnSettlements = new HashSet<FnSettlement>();
            this.FnSubJournals = new HashSet<FnSubJournal>();
        }
    
        public int AutoID { get; set; }
        public int Num { get; set; }
        public System.DateTime JournalDate { get; set; }
        public int YearID { get; set; }
        public int MonthID { get; set; }
        public string Statement { get; set; }
        public Nullable<int> N5ID { get; set; }
        public Nullable<System.DateTime> N5Date { get; set; }
        public string N5Statement { get; set; }
        public Nullable<int> N5DirectionID { get; set; }
        public Nullable<decimal> N5ExpensesAmount { get; set; }
        public Nullable<decimal> N5DeductsAmount { get; set; }
        public Nullable<decimal> N5NetAmount { get; set; }
        public decimal TotalAmount { get; set; }
        public string Details { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public int ProcessType { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual FnN5s FnN5s { get; set; }
        public virtual WfProcess WfProcess { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnSettlement> FnSettlements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnSubJournal> FnSubJournals { get; set; }
    }
}
