//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnPaymentOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FnPaymentOrder()
        {
            this.FnPaymentEmps = new HashSet<FnPaymentEmp>();
            this.FnSubPaymentOrders = new HashSet<FnSubPaymentOrder>();
        }
    
        public int AutoID { get; set; }
        public int YearID { get; set; }
        public int MonthID { get; set; }
        public int Num { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int N5ID { get; set; }
        public int BenfitType { get; set; }
        public Nullable<int> BenfitCompanyID { get; set; }
        public Nullable<int> BenfitDirectionID { get; set; }
        public int BenfitBankID { get; set; }
        public int BenfitCountryID { get; set; }
        public string BenfitNum { get; set; }
        public string BenfitAccountNum { get; set; }
        public int CurrencyID { get; set; }
        public int PayementWay { get; set; }
        public Nullable<int> LegalRespID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string Details { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> ProcessType { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string BenfitName { get; set; }
        public Nullable<decimal> ForeignAmount { get; set; }
        public string BenfitDetails { get; set; }
        public Nullable<int> DisscountBenfitID { get; set; }
        public string PStatement { get; set; }
        public string BenfitPhoneNumber { get; set; }
    
        public virtual FnN5s FnN5s { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnPaymentEmp> FnPaymentEmps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FnSubPaymentOrder> FnSubPaymentOrders { get; set; }
    }
}
