//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FnReciptVoucher
    {
        public long AutoID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string Name { get; set; }
        public string Num { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> YearID { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> VoucherType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public string VoucherTypeInfo { get; set; }
        public Nullable<bool> IsFn { get; set; }
        public string BankName { get; set; }
        public string SheckNo { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> BankID { get; set; }
        public Nullable<int> FromTypeId { get; set; }
        public Nullable<int> FromAccountId { get; set; }
        public Nullable<int> FromOpId { get; set; }
        public Nullable<int> FromInvoiceId { get; set; }
        public Nullable<int> ToTypeId { get; set; }
        public Nullable<int> ToAccountId { get; set; }
        public Nullable<int> ToOpId { get; set; }
        public Nullable<int> ToInvoiceId { get; set; }
    }
}
