//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrAdvance
    {
        public int AutoID { get; set; }
        public int DirectionID { get; set; }
        public int Year { get; set; }
        public Nullable<int> TempAdvance { get; set; }
        public Nullable<System.DateTime> AdvaceDate { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<int> SecretAdvance { get; set; }
        public string OtherAdvances { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
    }
}
