//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LbBrAnalysisMaterial
    {
        public int AutoID { get; set; }
        public Nullable<int> AnalysisID { get; set; }
        public Nullable<int> MaterialType { get; set; }
        public Nullable<int> MaterialID { get; set; }
        public Nullable<decimal> MaterialPercent { get; set; }
        public string Details { get; set; }
    
        public virtual LbAnalys LbAnalys { get; set; }
        public virtual LbClassification LbClassification { get; set; }
    }
}
