//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LbClassification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LbClassification()
        {
            this.LbAnalyses = new HashSet<LbAnalys>();
            this.LbAnalyses1 = new HashSet<LbAnalys>();
            this.LbAnalyses2 = new HashSet<LbAnalys>();
            this.LbAnalyses3 = new HashSet<LbAnalys>();
            this.LbAnalyses4 = new HashSet<LbAnalys>();
            this.LbAnalyses5 = new HashSet<LbAnalys>();
            this.LbAnalyses6 = new HashSet<LbAnalys>();
            this.LbAnalyses7 = new HashSet<LbAnalys>();
            this.LbBrAnalysisMaterials = new HashSet<LbBrAnalysisMaterial>();
            this.LbClassifications1 = new HashSet<LbClassification>();
            this.LbIssues = new HashSet<LbIssue>();
            this.LbIssues1 = new HashSet<LbIssue>();
            this.LbIssues2 = new HashSet<LbIssue>();
            this.LbIssues3 = new HashSet<LbIssue>();
            this.LbIssues4 = new HashSet<LbIssue>();
            this.LbIssues5 = new HashSet<LbIssue>();
            this.LbSamples = new HashSet<LbSample>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string EnName { get; set; }
        public string HsNum { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Details { get; set; }
        public int ParentID { get; set; }
        public Nullable<int> PrimaryID { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbAnalys> LbAnalyses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbAnalys> LbAnalyses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbAnalys> LbAnalyses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbAnalys> LbAnalyses3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbAnalys> LbAnalyses4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbAnalys> LbAnalyses5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbAnalys> LbAnalyses6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbAnalys> LbAnalyses7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbBrAnalysisMaterial> LbBrAnalysisMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbClassification> LbClassifications1 { get; set; }
        public virtual LbClassification LbClassification1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbIssue> LbIssues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbIssue> LbIssues1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbIssue> LbIssues2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbIssue> LbIssues3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbIssue> LbIssues4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbIssue> LbIssues5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LbSample> LbSamples { get; set; }
    }
}
