//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LfIssuesReceiver
    {
        public int AutoID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Employee Employee3 { get; set; }
    }
}
