//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MgAppointement
    {
        public int AutoID { get; set; }
        public int RequestNum { get; set; }
        public int YearID { get; set; }
        public int DirectionID { get; set; }
        public int PositionID { get; set; }
        public System.DateTime VisitDate { get; set; }
        public int VisitTime { get; set; }
        public int VisitDuration { get; set; }
        public int VisitState { get; set; }
        public bool IsFromIn { get; set; }
        public string Title { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> EmpDirectionID { get; set; }
        public Nullable<int> VisitorID { get; set; }
        public string DirectionName { get; set; }
        public string MobileNum { get; set; }
        public string Reason { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual ClsDirection ClsDirection1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
