//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MlExit
    {
        public int AutoID { get; set; }
        public int RequestNum { get; set; }
        public string YearID { get; set; }
        public int DirectionID { get; set; }
        public int DepartmentID { get; set; }
        public int GateID { get; set; }
        public int EmpID { get; set; }
        public System.DateTime PDate { get; set; }
        public bool IsLeave { get; set; }
        public Nullable<int> TimeFrom { get; set; }
        public Nullable<int> TimeTo { get; set; }
        public Nullable<int> ManagerID { get; set; }
        public Nullable<bool> IsExited { get; set; }
        public Nullable<int> ExitTime { get; set; }
        public Nullable<bool> IsReturned { get; set; }
        public Nullable<int> ReturnTime { get; set; }
        public string Reason { get; set; }
        public string Details { get; set; }
        public string OutDetails { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public int ProcessType { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual ClsGate ClsGate { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
    }
}
