//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPortalServerLink
    {
        public int AutoID { get; set; }
        public string MainServer { get; set; }
        public Nullable<int> WebId { get; set; }
        public string SecondServer { get; set; }
        public string BackupServer { get; set; }
        public string ApiServer1 { get; set; }
        public string ApiServer2 { get; set; }
        public string ApiServer3 { get; set; }
        public string MobileServer1 { get; set; }
        public string MobileServer2 { get; set; }
        public string Dashboard1 { get; set; }
        public string Dashboard2 { get; set; }
        public string Dashboard3 { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> WebsiteID { get; set; }
    
        public virtual MyPortalWebsite MyPortalWebsite { get; set; }
    }
}
