//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyPortalElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MyPortalElement()
        {
            this.MyPortalElementsImages = new HashSet<MyPortalElementsImage>();
        }
    
        public int AutoID { get; set; }
        public Nullable<int> WebSiteID { get; set; }
        public Nullable<int> SectionID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Type { get; set; }
        public string Content { get; set; }
        public string ExternalLink { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public string Tags { get; set; }
        public Nullable<bool> Level { get; set; }
        public Nullable<bool> Templete { get; set; }
        public Nullable<long> Picture1 { get; set; }
        public Nullable<long> Picture2 { get; set; }
        public string Group { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<System.DateTime> StartDate_ { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<bool> CommentsAllow { get; set; }
        public string Icon { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyPortalElementsImage> MyPortalElementsImages { get; set; }
    }
}
