//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NICSubestance
    {
        public long AutoID { get; set; }
        public long IssueID { get; set; }
        public string IssueName { get; set; }
        public Nullable<double> Qnt { get; set; }
        public Nullable<double> Qnt2 { get; set; }
        public Nullable<double> Qnt3 { get; set; }
        public string SubestanceName { get; set; }
        public Nullable<int> SubestanceID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> SubestanceUnitID { get; set; }
        public int IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
