//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrBrCommLevel
    {
        public int AutoID { get; set; }
        public Nullable<int> LevelID { get; set; }
        public Nullable<int> CommittyID { get; set; }
        public Nullable<int> LevelsCount { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ClsLevel ClsLevel { get; set; }
        public virtual PrCommitty PrCommitty { get; set; }
    }
}
