//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcCommissioning
    {
        public int AutoID { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderAdmin { get; set; }
        public int EmpID { get; set; }
        public bool EmpIsOn { get; set; }
        public int EmpDirection { get; set; }
        public int DirectionType { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> DaysCount { get; set; }
        public string Details { get; set; }
        public int System { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual ClsDepartmentsStructure ClsDepartmentsStructure { get; set; }
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual ClsDirection ClsDirection1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
