//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcDelegate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RcDelegate()
        {
            this.IntIntedabsCities = new HashSet<IntIntedabsCity>();
            this.IntIntedabsCountries = new HashSet<IntIntedabsCountry>();
        }
    
        public int AutoID { get; set; }
        public int EmpID { get; set; }
        public Nullable<int> EmpLevel { get; set; }
        public Nullable<bool> EmpIsOn { get; set; }
        public Nullable<int> EmpDirection { get; set; }
        public Nullable<int> EmpDirection1 { get; set; }
        public Nullable<int> EmpDirection2 { get; set; }
        public Nullable<int> EmpDirection3 { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderAdmin { get; set; }
        public Nullable<bool> IsInside { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int FinYearID { get; set; }
        public int Period { get; set; }
        public string Destination { get; set; }
        public string Reason { get; set; }
        public Nullable<int> BalanceType { get; set; }
        public string IncOrderNum { get; set; }
        public Nullable<System.DateTime> IncOrderDate { get; set; }
        public string IncOrderAdmin { get; set; }
        public string Details { get; set; }
        public int SystemID { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> RequestID { get; set; }
        public bool IsFromRequest { get; set; }
        public Nullable<int> EmpDepartment { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public string CancelOrderNum { get; set; }
        public Nullable<System.DateTime> CancelOrderDate { get; set; }
        public Nullable<bool> IsDelayed { get; set; }
        public string DelayOrderNum { get; set; }
        public Nullable<System.DateTime> DelayOrderDate { get; set; }
        public Nullable<int> DelayDaysCount { get; set; }
        public Nullable<System.DateTime> DelayStartDate { get; set; }
        public Nullable<int> YearNum { get; set; }
        public string OutGoingNum { get; set; }
        public Nullable<System.DateTime> OutGoingDate { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual ClsDirection ClsDirection1 { get; set; }
        public virtual ClsDirection ClsDirection2 { get; set; }
        public virtual ClsLevel ClsLevel { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual IntIntedabRequest IntIntedabRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntIntedabsCity> IntIntedabsCities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IntIntedabsCountry> IntIntedabsCountries { get; set; }
        public virtual RcDelegate RcDelegates1 { get; set; }
        public virtual RcDelegate RcDelegate1 { get; set; }
    }
}
