//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcEmpsCommunication
    {
        public int AutoID { get; set; }
        public int EmpID { get; set; }
        public string CommunicationName { get; set; }
        public int CommunicationType { get; set; }
        public int OrderBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual RcEmpsDecumentationsType RcEmpsDecumentationsType { get; set; }
    }
}
