//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcEmpsAddress
    {
        public int AutoID { get; set; }
        public int EmpID { get; set; }
        public Nullable<long> AddressID { get; set; }
        public string AddressDetails { get; set; }
        public int AddressType { get; set; }
        public int OrderBy { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
