//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RcEmpsDocumentation
    {
        public long AutoID { get; set; }
        public int EmpID { get; set; }
        public long FileID { get; set; }
        public int DocTypeID { get; set; }
    
        public virtual ClsArchiveFile ClsArchiveFile { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RcEmpsDecumentationsType RcEmpsDecumentationsType { get; set; }
    }
}
