//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptsMember
    {
        public long AutoID { get; set; }
        public int ReceiptID { get; set; }
        public int EmpID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Receipt Receipt { get; set; }
    }
}
