//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RtDue
    {
        public int AutoID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> EmpSystem { get; set; }
        public Nullable<int> EmpLevel { get; set; }
        public Nullable<int> EmpDirection1 { get; set; }
        public string OrderNum { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderAdmin { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> EndReasonType { get; set; }
        public Nullable<int> EndReasonID { get; set; }
        public Nullable<bool> IsSimpleAccount { get; set; }
        public Nullable<decimal> Vacations0 { get; set; }
        public Nullable<decimal> Vacations1 { get; set; }
        public Nullable<decimal> Vacations2 { get; set; }
        public Nullable<decimal> Vacations3 { get; set; }
        public Nullable<decimal> WorkingDays0 { get; set; }
        public Nullable<decimal> WorkingDays1 { get; set; }
        public Nullable<decimal> WorkingDays2 { get; set; }
        public Nullable<decimal> WorkingDays3 { get; set; }
        public Nullable<decimal> Compensate0 { get; set; }
        public Nullable<decimal> Compensate1 { get; set; }
        public Nullable<decimal> Compensate2 { get; set; }
        public Nullable<decimal> Compensate3 { get; set; }
        public Nullable<decimal> Deserve0 { get; set; }
        public Nullable<decimal> Deserve1 { get; set; }
        public Nullable<decimal> Deserve2 { get; set; }
        public Nullable<decimal> Deserve3 { get; set; }
        public Nullable<decimal> Reset0 { get; set; }
        public Nullable<decimal> Reset1 { get; set; }
        public Nullable<decimal> Reset2 { get; set; }
        public Nullable<decimal> Reset3 { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
