//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScCategory()
        {
            this.MyPortalSectionCategories = new HashSet<MyPortalSectionCategory>();
            this.ScProductsCategories = new HashSet<ScProductsCategory>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsFirstLevel { get; set; }
        public string Details { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<long> ImageID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string Icon { get; set; }
        public Nullable<int> ShowInMenus { get; set; }
        public Nullable<int> ShowOptions { get; set; }
        public Nullable<bool> Classification { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public string CategoryCode { get; set; }
        public string NameEn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyPortalSectionCategory> MyPortalSectionCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScProductsCategory> ScProductsCategories { get; set; }
    }
}
