//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScCommissionsEmployee
    {
        public int AutoID { get; set; }
        public Nullable<int> CommissionID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ScCommission ScCommission { get; set; }
    }
}
