//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScGiftCoupon
    {
        public long AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Code { get; set; }
        public string ActiveCode { get; set; }
        public string SentMobile { get; set; }
        public decimal Amount { get; set; }
        public Nullable<decimal> Points { get; set; }
        public string Details { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public string Link { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<decimal> UsedAmount { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
    
        public virtual ScClient ScClient { get; set; }
        public virtual ScClient ScClient1 { get; set; }
    }
}
