//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScInventoriesIn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScInventoriesIn()
        {
            this.ScSubInventoriesIns = new HashSet<ScSubInventoriesIn>();
        }
    
        public int AutoID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> InventoryOutID { get; set; }
        public Nullable<int> PurchaseInvoiceID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> OperationID { get; set; }
        public Nullable<int> YearId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubInventoriesIn> ScSubInventoriesIns { get; set; }
    }
}
