//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScPackage()
        {
            this.FeUsersRatings = new HashSet<FeUsersRating>();
            this.MyPortalSectionProducts = new HashSet<MyPortalSectionProduct>();
            this.ScMarkterGroupSubs = new HashSet<ScMarkterGroupSub>();
            this.ScPackagesAttributes = new HashSet<ScPackagesAttribute>();
            this.ScPackagesDetails = new HashSet<ScPackagesDetail>();
            this.ScPackagesImages = new HashSet<ScPackagesImage>();
            this.ScSubProcessesDamagedStocks = new HashSet<ScSubProcessesDamagedStock>();
            this.ScProductPrices = new HashSet<ScProductPrice>();
            this.ScSubDataTranferInventories = new HashSet<ScSubDataTranferInventory>();
            this.ScSubInventories = new HashSet<ScSubInventory>();
            this.ScSubPurchaseRequests = new HashSet<ScSubPurchaseRequest>();
            this.ScSubPurchaseReturns = new HashSet<ScSubPurchaseReturn>();
            this.ScSubSalesRequests = new HashSet<ScSubSalesRequest>();
            this.ScSubSpecialOffers = new HashSet<ScSubSpecialOffer>();
            this.ScSubSpecialOffers2 = new HashSet<ScSubSpecialOffers2>();
            this.ScPackagesAddons = new HashSet<ScPackagesAddon>();
            this.ScPackagesAddons1 = new HashSet<ScPackagesAddon>();
            this.ScSubInventoriesIns = new HashSet<ScSubInventoriesIn>();
            this.ScSubInventoriesOuts = new HashSet<ScSubInventoriesOut>();
            this.ScSubInventoryProcesses = new HashSet<ScSubInventoryProcess>();
            this.ScSubInventoryProcessesContinues = new HashSet<ScSubInventoryProcessesContinue>();
            this.ScSubPurchaseInvoices = new HashSet<ScSubPurchaseInvoice>();
            this.ScPackagesBundles = new HashSet<ScPackagesBundle>();
            this.ScSubPackagesBundles = new HashSet<ScSubPackagesBundle>();
            this.ScSubSalesInvoices = new HashSet<ScSubSalesInvoice>();
            this.ScSubSalesReturns = new HashSet<ScSubSalesReturn>();
        }
    
        public long AutoID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string PkgNo { get; set; }
        public string PkgName { get; set; }
        public string SubPkgNo { get; set; }
        public string SubPkgName { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> NewPkg { get; set; }
        public Nullable<bool> SpecialPkg { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string BarCode { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public string SKU { get; set; }
        public string UPC { get; set; }
        public string GroupCode { get; set; }
        public Nullable<long> GuaranteePlan { get; set; }
        public string EngName { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public string MetaWord { get; set; }
        public Nullable<int> PointCategory { get; set; }
        public Nullable<int> MeasureType { get; set; }
        public Nullable<int> NotifyQty { get; set; }
        public Nullable<int> NotifyTime { get; set; }
        public Nullable<int> NotifySale { get; set; }
        public string Pic360 { get; set; }
        public Nullable<bool> IsSale { get; set; }
        public Nullable<bool> IsToInv { get; set; }
        public Nullable<bool> IsPriceless { get; set; }
        public string StoreMetaData { get; set; }
        public string FilterValue { get; set; }
        public string FilterText { get; set; }
        public Nullable<bool> IsMeasureMain { get; set; }
        public Nullable<decimal> MeasureCount { get; set; }
        public Nullable<long> MainPackageId { get; set; }
        public Nullable<bool> IsShowInStore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeUsersRating> FeUsersRatings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyPortalSectionProduct> MyPortalSectionProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScMarkterGroupSub> ScMarkterGroupSubs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScPackagesAttribute> ScPackagesAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScPackagesDetail> ScPackagesDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScPackagesImage> ScPackagesImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubProcessesDamagedStock> ScSubProcessesDamagedStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScProductPrice> ScProductPrices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubDataTranferInventory> ScSubDataTranferInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubInventory> ScSubInventories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubPurchaseRequest> ScSubPurchaseRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubPurchaseReturn> ScSubPurchaseReturns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubSalesRequest> ScSubSalesRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubSpecialOffer> ScSubSpecialOffers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubSpecialOffers2> ScSubSpecialOffers2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScPackagesAddon> ScPackagesAddons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScPackagesAddon> ScPackagesAddons1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubInventoriesIn> ScSubInventoriesIns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubInventoriesOut> ScSubInventoriesOuts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubInventoryProcess> ScSubInventoryProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubInventoryProcessesContinue> ScSubInventoryProcessesContinues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubPurchaseInvoice> ScSubPurchaseInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScPackagesBundle> ScPackagesBundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubPackagesBundle> ScSubPackagesBundles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubSalesInvoice> ScSubSalesInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubSalesReturn> ScSubSalesReturns { get; set; }
    }
}
