//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScPosRole
    {
        public int AutoID { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<bool> CanDiscount { get; set; }
        public Nullable<bool> CanSendCashPrice { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<bool> CanSalesReturn { get; set; }
        public Nullable<bool> CanRequestQnt { get; set; }
        public Nullable<bool> CanJard { get; set; }
        public Nullable<bool> CanScan { get; set; }
        public Nullable<bool> CanEditQnt { get; set; }
        public Nullable<bool> CanEditDiscount { get; set; }
        public Nullable<bool> CanEditPrice { get; set; }
        public Nullable<bool> CanCreateCoupon { get; set; }
        public Nullable<bool> CanProcessBox { get; set; }
        public Nullable<bool> Cansales { get; set; }
        public Nullable<bool> Canprepare { get; set; }
        public Nullable<bool> Canrent { get; set; }
        public Nullable<bool> Cansubscribe { get; set; }
        public Nullable<bool> Canreserve { get; set; }
        public Nullable<bool> CanManufactoring { get; set; }
        public Nullable<bool> CanJardManufactoring { get; set; }
        public Nullable<bool> CanInvOut { get; set; }
        public Nullable<bool> CanInvIn { get; set; }
        public Nullable<bool> CanTalf { get; set; }
    }
}
