//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScPosBox
    {
        public long AutoID { get; set; }
        public Nullable<long> ShiftID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> ProcessType { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public Nullable<int> EmpFrom { get; set; }
        public Nullable<int> EmpTo { get; set; }
    }
}
