//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScProductPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScProductPrice()
        {
            this.ScSubProductPricesServices = new HashSet<ScSubProductPricesService>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<long> PackageID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> SpecialPrice { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<decimal> PriceLimit { get; set; }
        public string PriceCode { get; set; }
        public Nullable<bool> PricewithTax { get; set; }
        public Nullable<int> PriceType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubProductPricesService> ScSubProductPricesServices { get; set; }
        public virtual ScPackage ScPackage { get; set; }
    }
}
