//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScRelatedProduct
    {
        public long AutoID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> RelatedProductID { get; set; }
    
        public virtual ScProduct ScProduct { get; set; }
        public virtual ScProduct ScProduct1 { get; set; }
    }
}
