//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSalesOrderProcess
    {
        public long AutoID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public string details { get; set; }
        public Nullable<int> YearId { get; set; }
    
        public virtual ScSalesInvoice ScSalesInvoice { get; set; }
    }
}
