//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSalesInvoicesZatcaPIH
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceHash { get; set; }
        public string InvoiceQR { get; set; }
        public string Status { get; set; }
        public string InfoInvoice { get; set; }
        public string InfoClearedInvoice { get; set; }
        public string InfoTimestamp { get; set; }
        public string InfoMessage { get; set; }
        public string WarningsCategory { get; set; }
        public string WarningsCode { get; set; }
        public string WarningsMessage { get; set; }
        public string ErrorMsg { get; set; }
        public string ErrorsCategory { get; set; }
        public string ErrorsCode { get; set; }
        public string ErrorsMessage { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<long> ShiftId { get; set; }
        public Nullable<int> DeviceId { get; set; }
    }
}
