//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSalesInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScSalesInvoice()
        {
            this.FeUsersOrders = new HashSet<FeUsersOrder>();
            this.OpOperationOrders = new HashSet<OpOperationOrder>();
            this.ScSalesInvoicePaymentsTypes = new HashSet<ScSalesInvoicePaymentsType>();
            this.ScSalesInvoicesShippingAddresses = new HashSet<ScSalesInvoicesShippingAddress>();
            this.ScSalesOrderProcesses = new HashSet<ScSalesOrderProcess>();
            this.ScSubSalesExtraFees = new HashSet<ScSubSalesExtraFee>();
            this.ScSubSalesInvoiceTransactions = new HashSet<ScSubSalesInvoiceTransaction>();
            this.ScSubSalesInvoices = new HashSet<ScSubSalesInvoice>();
            this.ScSubSalesTaxes = new HashSet<ScSubSalesTax>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string FileNo { get; set; }
        public Nullable<int> SalesRequestNo { get; set; }
        public Nullable<int> SupplierNumber { get; set; }
        public string SupplierInvoiceNo { get; set; }
        public Nullable<int> SalesmanID { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<int> InvoicesStatus { get; set; }
        public System.DateTime InvoicesDate { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public int ProcessType { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> ShippingPackageID { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<bool> IsCommision { get; set; }
        public Nullable<decimal> TotalCommision { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<int> GidNum { get; set; }
        public Nullable<int> SalesType { get; set; }
        public Nullable<bool> IsInv { get; set; }
        public Nullable<bool> IsFn { get; set; }
        public Nullable<System.DateTime> DeliveryTime { get; set; }
        public string PriceCode { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> ShippingStatus { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<int> ShippingProcess { get; set; }
        public Nullable<int> ShippingCompanyID { get; set; }
        public string OfflineInvoiceName { get; set; }
        public Nullable<long> ShiftId { get; set; }
        public string ReportH { get; set; }
        public string ReportF { get; set; }
        public Nullable<decimal> SsPackagePrice { get; set; }
        public Nullable<decimal> SsServicePrice { get; set; }
        public Nullable<decimal> SsDiscount { get; set; }
        public Nullable<decimal> SsPackageTax { get; set; }
        public Nullable<decimal> SsServiceTax { get; set; }
        public Nullable<decimal> SsTaxableTotal { get; set; }
        public Nullable<decimal> SsTotalPrice { get; set; }
        public Nullable<decimal> SsQty { get; set; }
        public Nullable<decimal> SsCost { get; set; }
        public Nullable<decimal> SsPaid { get; set; }
        public Nullable<decimal> SsPaidCash { get; set; }
        public Nullable<decimal> SsPaidDebit { get; set; }
        public Nullable<decimal> SsPaidCredit { get; set; }
        public Nullable<decimal> SsPaidPoint { get; set; }
        public Nullable<decimal> SsPaidOther { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeUsersOrder> FeUsersOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpOperationOrder> OpOperationOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSalesInvoicePaymentsType> ScSalesInvoicePaymentsTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSalesInvoicesShippingAddress> ScSalesInvoicesShippingAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSalesOrderProcess> ScSalesOrderProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubSalesExtraFee> ScSubSalesExtraFees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubSalesInvoiceTransaction> ScSubSalesInvoiceTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubSalesInvoice> ScSubSalesInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScSubSalesTax> ScSubSalesTaxes { get; set; }
    }
}
