//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSalesInvoicesSummary
    {
        public int AutoID { get; set; }
        public int InvoiceID { get; set; }
        public long WebsiteID { get; set; }
        public Nullable<decimal> SsPackagePrice { get; set; }
        public Nullable<decimal> SsServicePrice { get; set; }
        public Nullable<decimal> SsDiscount { get; set; }
        public Nullable<decimal> SsPackageTax { get; set; }
        public Nullable<decimal> SsServiceTax { get; set; }
        public Nullable<decimal> SsTaxableTotal { get; set; }
        public Nullable<decimal> SsTotalPrice { get; set; }
        public Nullable<decimal> SsQty { get; set; }
        public Nullable<decimal> SsCost { get; set; }
        public Nullable<decimal> SsPaid { get; set; }
        public Nullable<decimal> SsPaidCash { get; set; }
        public Nullable<decimal> SsPaidDebit { get; set; }
        public Nullable<decimal> SsPaidCredit { get; set; }
        public Nullable<decimal> SsPaidPoint { get; set; }
        public Nullable<decimal> SsPaidOther { get; set; }
        public string Details { get; set; }
    }
}
