//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSubSalesInvoice
    {
        public int AutoID { get; set; }
        public Nullable<long> PackageID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> ShippingCampanyID { get; set; }
        public Nullable<decimal> Qnt { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> MarkterCommisions { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public string SN { get; set; }
        public string Code { get; set; }
    
        public virtual ScPackage ScPackage { get; set; }
        public virtual ScSalesInvoice ScSalesInvoice { get; set; }
    }
}
