//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSubSalesTax
    {
        public int AutoID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<int> TaxTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> TaxPercentage { get; set; }
        public string Details { get; set; }
        public string Code { get; set; }
    
        public virtual ScSalesInvoice ScSalesInvoice { get; set; }
        public virtual FnTaxesType FnTaxesType { get; set; }
    }
}
