//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSubPackagesBundle
    {
        public int AutoID { get; set; }
        public Nullable<long> BundleID { get; set; }
        public Nullable<long> PackageID { get; set; }
        public Nullable<decimal> Qnt { get; set; }
        public string Note { get; set; }
    
        public virtual ScPackage ScPackage { get; set; }
        public virtual ScPackagesBundle ScPackagesBundle { get; set; }
    }
}
