//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSubSalesInvoiceTransaction
    {
        public int AutoID { get; set; }
        public Nullable<int> TrType { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> TransactionPrice { get; set; }
        public string TransactionNo { get; set; }
        public string Details { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public string Name { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<int> BankId { get; set; }
        public string BankAccount { get; set; }
    
        public virtual ScSalesInvoice ScSalesInvoice { get; set; }
    }
}
