//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSubPurchaseInvoice
    {
        public int AutoID { get; set; }
        public Nullable<long> PackageID { get; set; }
        public Nullable<int> InvoiceID { get; set; }
        public Nullable<decimal> Qnt { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<decimal> PriceWithTax { get; set; }
        public Nullable<bool> IsPriceTax { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
    
        public virtual ScPackage ScPackage { get; set; }
        public virtual ScPurchasesInvoice ScPurchasesInvoice { get; set; }
    }
}
