//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScSubInventoryProcessesContinue
    {
        public int AutoID { get; set; }
        public Nullable<long> PackageID { get; set; }
        public Nullable<int> InventoryProcessID { get; set; }
        public Nullable<decimal> CurrentQnt { get; set; }
        public Nullable<decimal> Qnt { get; set; }
        public Nullable<decimal> DiffQnt { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Location { get; set; }
        public string Details { get; set; }
    
        public virtual ScInventoryProcessesContinue ScInventoryProcessesContinue { get; set; }
        public virtual ScPackage ScPackage { get; set; }
    }
}
