//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScWorkShift
    {
        public long AutoID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> StartAmount { get; set; }
        public Nullable<decimal> EndAmount { get; set; }
        public Nullable<int> ReceivedFrom { get; set; }
        public Nullable<int> DepositTo { get; set; }
        public Nullable<int> WebsiteID { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> InventoryId { get; set; }
        public Nullable<long> OfflineId { get; set; }
        public Nullable<int> SystemType { get; set; }
    }
}
