//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionLogApi
    {
        public long AutoID { get; set; }
        public int OperationID { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public string HeaderContent { get; set; }
        public string BodyContent { get; set; }
        public string ResponseContent { get; set; }
        public string ApiName { get; set; }
    }
}
