//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShoppingCartConnection : DbContext
    {
        public ShoppingCartConnection()
            : base("name=ShoppingCartConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeePosAuth> EmployeePosAuths { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FeChangePassword> FeChangePasswords { get; set; }
        public virtual DbSet<FeRating> FeRatings { get; set; }
        public virtual DbSet<FeTempCart> FeTempCarts { get; set; }
        public virtual DbSet<FeUser> FeUsers { get; set; }
        public virtual DbSet<FeUsersOrder> FeUsersOrders { get; set; }
        public virtual DbSet<FeUsersRating> FeUsersRatings { get; set; }
        public virtual DbSet<FeUsersStatictic> FeUsersStatictics { get; set; }
        public virtual DbSet<FeUsersSubscription> FeUsersSubscriptions { get; set; }
        public virtual DbSet<MyPortalCurrency> MyPortalCurrencies { get; set; }
        public virtual DbSet<MyPortalDesign> MyPortalDesigns { get; set; }
        public virtual DbSet<MyPortalElement> MyPortalElements { get; set; }
        public virtual DbSet<MyPortalElementsImage> MyPortalElementsImages { get; set; }
        public virtual DbSet<MyPortalEmail> MyPortalEmails { get; set; }
        public virtual DbSet<MyPortalLanguage> MyPortalLanguages { get; set; }
        public virtual DbSet<MyPortalPage> MyPortalPages { get; set; }
        public virtual DbSet<MyPortalSectionCategory> MyPortalSectionCategories { get; set; }
        public virtual DbSet<MyPortalSectionProduct> MyPortalSectionProducts { get; set; }
        public virtual DbSet<MyPortalSection> MyPortalSections { get; set; }
        public virtual DbSet<MyPortalService> MyPortalServices { get; set; }
        public virtual DbSet<MyPortalTemplate> MyPortalTemplates { get; set; }
        public virtual DbSet<MyPortalWebsite> MyPortalWebsites { get; set; }
        public virtual DbSet<ScAttribute> ScAttributes { get; set; }
        public virtual DbSet<ScBanksAccount> ScBanksAccounts { get; set; }
        public virtual DbSet<ScCategory> ScCategories { get; set; }
        public virtual DbSet<ScCommission> ScCommissions { get; set; }
        public virtual DbSet<ScCommissionsEmployee> ScCommissionsEmployees { get; set; }
        public virtual DbSet<ScInventoriesIn> ScInventoriesIns { get; set; }
        public virtual DbSet<ScInventoriesOut> ScInventoriesOuts { get; set; }
        public virtual DbSet<ScInventoryEmployee> ScInventoryEmployees { get; set; }
        public virtual DbSet<ScInventoryProcess> ScInventoryProcesses { get; set; }
        public virtual DbSet<ScMarkterGroup> ScMarkterGroups { get; set; }
        public virtual DbSet<ScMarkterGroupSub> ScMarkterGroupSubs { get; set; }
        public virtual DbSet<ScMarkterPromo> ScMarkterPromos { get; set; }
        public virtual DbSet<ScPackageHistory> ScPackageHistories { get; set; }
        public virtual DbSet<ScPackagesAttribute> ScPackagesAttributes { get; set; }
        public virtual DbSet<ScPackagesImage> ScPackagesImages { get; set; }
        public virtual DbSet<ScPaymentSetting> ScPaymentSettings { get; set; }
        public virtual DbSet<ScProductCost> ScProductCosts { get; set; }
        public virtual DbSet<ScProductPrice> ScProductPrices { get; set; }
        public virtual DbSet<ScProductsCategory> ScProductsCategories { get; set; }
        public virtual DbSet<ScProductsImage> ScProductsImages { get; set; }
        public virtual DbSet<ScPurchaseReturn> ScPurchaseReturns { get; set; }
        public virtual DbSet<ScPurchasesInvoice> ScPurchasesInvoices { get; set; }
        public virtual DbSet<ScPurchasesRequest> ScPurchasesRequests { get; set; }
        public virtual DbSet<ScRelatedProduct> ScRelatedProducts { get; set; }
        public virtual DbSet<ScSalesRequest> ScSalesRequests { get; set; }
        public virtual DbSet<ScService> ScServices { get; set; }
        public virtual DbSet<ScShipmentNaqel> ScShipmentNaqels { get; set; }
        public virtual DbSet<ScShipmentRequest> ScShipmentRequests { get; set; }
        public virtual DbSet<ScShippingCompany> ScShippingCompanies { get; set; }
        public virtual DbSet<ScShippingCompanyFromCity> ScShippingCompanyFromCities { get; set; }
        public virtual DbSet<ScShippingCompanyToCity> ScShippingCompanyToCities { get; set; }
        public virtual DbSet<ScSpecialOffer> ScSpecialOffers { get; set; }
        public virtual DbSet<ScSpecialOffersService> ScSpecialOffersServices { get; set; }
        public virtual DbSet<ScSubClientMarkter> ScSubClientMarkters { get; set; }
        public virtual DbSet<ScSubCommission> ScSubCommissions { get; set; }
        public virtual DbSet<ScSubInventory> ScSubInventories { get; set; }
        public virtual DbSet<ScSubProductPricesService> ScSubProductPricesServices { get; set; }
        public virtual DbSet<ScSubPurchaseExtraFee> ScSubPurchaseExtraFees { get; set; }
        public virtual DbSet<ScSubPurchaseReturn> ScSubPurchaseReturns { get; set; }
        public virtual DbSet<ScSubSalesRequest> ScSubSalesRequests { get; set; }
        public virtual DbSet<ScSubSpecialOffer> ScSubSpecialOffers { get; set; }
        public virtual DbSet<ScSuplierEvaluation> ScSuplierEvaluations { get; set; }
        public virtual DbSet<SysScreen> SysScreens { get; set; }
        public virtual DbSet<SysPage> SysPages { get; set; }
        public virtual DbSet<VwGDNCDocumentsStore> VwGDNCDocumentsStores { get; set; }
        public virtual DbSet<PosSale> PosSales { get; set; }
        public virtual DbSet<FnFinYear> FnFinYears { get; set; }
        public virtual DbSet<ScSalesInvoicePaymentsType> ScSalesInvoicePaymentsTypes { get; set; }
        public virtual DbSet<ScPosBox> ScPosBoxes { get; set; }
        public virtual DbSet<VwPackageHistory> VwPackageHistories { get; set; }
        public virtual DbSet<ClsMeasureType> ClsMeasureTypes { get; set; }
        public virtual DbSet<ScSubPurchaseRequest> ScSubPurchaseRequests { get; set; }
        public virtual DbSet<ScInventoryProcessesContinue> ScInventoryProcessesContinues { get; set; }
        public virtual DbSet<NfNotification> NfNotifications { get; set; }
        public virtual DbSet<NfType> NfTypes { get; set; }
        public virtual DbSet<NfBrUser> NfBrUsers { get; set; }
        public virtual DbSet<EmployeePosAuthentication> EmployeePosAuthentications { get; set; }
        public virtual DbSet<ScPayQitaf> ScPayQitafs { get; set; }
        public virtual DbSet<ScPayStc> ScPayStcs { get; set; }
        public virtual DbSet<ScPointCategory> ScPointCategories { get; set; }
        public virtual DbSet<ScOfflinePOS> ScOfflinePOS { get; set; }
        public virtual DbSet<ScPosRole> ScPosRoles { get; set; }
        public virtual DbSet<FeUsersAddress> FeUsersAddresses { get; set; }
        public virtual DbSet<ScSalesInvoicesShippingAddress> ScSalesInvoicesShippingAddresses { get; set; }
        public virtual DbSet<PsPost> PsPosts { get; set; }
        public virtual DbSet<PsSeenPost> PsSeenPosts { get; set; }
        public virtual DbSet<ClsVidLibrary> ClsVidLibraries { get; set; }
        public virtual DbSet<MgClassification> MgClassifications { get; set; }
        public virtual DbSet<MgBfRqOrder> MgBfRqOrders { get; set; }
        public virtual DbSet<MgBuffetOrder> MgBuffetOrders { get; set; }
        public virtual DbSet<ClsDirectionDepartment> ClsDirectionDepartments { get; set; }
        public virtual DbSet<ClsDirection> ClsDirections { get; set; }
        public virtual DbSet<ClsDepartmentsStructure> ClsDepartmentsStructures { get; set; }
        public virtual DbSet<SessionLogApi> SessionLogApis { get; set; }
        public virtual DbSet<SysErrorMessage> SysErrorMessages { get; set; }
        public virtual DbSet<ScSubSalesInvoiceTransaction> ScSubSalesInvoiceTransactions { get; set; }
        public virtual DbSet<ScSalesOrderProcess> ScSalesOrderProcesses { get; set; }
        public virtual DbSet<ScShippingPackage> ScShippingPackages { get; set; }
        public virtual DbSet<ScGiftPoint> ScGiftPoints { get; set; }
        public virtual DbSet<ScOnlinePOS> ScOnlinePOS { get; set; }
        public virtual DbSet<ClsCity> ClsCities { get; set; }
        public virtual DbSet<ClsCountry> ClsCountries { get; set; }
        public virtual DbSet<ScPackagesDetail> ScPackagesDetails { get; set; }
        public virtual DbSet<ScWorkShift> ScWorkShifts { get; set; }
        public virtual DbSet<SMSMessage> SMSMessages { get; set; }
        public virtual DbSet<OfflineInvoicePayment> OfflineInvoicePayments { get; set; }
        public virtual DbSet<OfflineInvoiceProduct> OfflineInvoiceProducts { get; set; }
        public virtual DbSet<OfflineInvoiceService> OfflineInvoiceServices { get; set; }
        public virtual DbSet<OfflineScSalesInvoice> OfflineScSalesInvoices { get; set; }
        public virtual DbSet<ScWorkShiftsMoney> ScWorkShiftsMoneys { get; set; }
        public virtual DbSet<SMSContact> SMSContacts { get; set; }
        public virtual DbSet<SMSGroup> SMSGroups { get; set; }
        public virtual DbSet<SMSMessagesTemplete> SMSMessagesTempletes { get; set; }
        public virtual DbSet<SMSMessageTempleteEmployee> SMSMessageTempleteEmployees { get; set; }
        public virtual DbSet<ScOnlinePOSClient> ScOnlinePOSClients { get; set; }
        public virtual DbSet<ScSalesReturnInvoicePaymentsType> ScSalesReturnInvoicePaymentsTypes { get; set; }
        public virtual DbSet<ScGiftCoupon> ScGiftCoupons { get; set; }
        public virtual DbSet<ClsPaymentType> ClsPaymentTypes { get; set; }
        public virtual DbSet<ScPaymentType> ScPaymentTypes { get; set; }
        public virtual DbSet<ClsTransactionType> ClsTransactionTypes { get; set; }
        public virtual DbSet<ScTransactionType> ScTransactionTypes { get; set; }
        public virtual DbSet<ScPriceCodeProduct> ScPriceCodeProducts { get; set; }
        public virtual DbSet<ScSubSpecialOffers2> ScSubSpecialOffers2 { get; set; }
        public virtual DbSet<ClsInvoicePaymentType> ClsInvoicePaymentTypes { get; set; }
        public virtual DbSet<ScMissingBarcode> ScMissingBarcodes { get; set; }
        public virtual DbSet<ScPosDevice> ScPosDevices { get; set; }
        public virtual DbSet<ScProductRating> ScProductRatings { get; set; }
        public virtual DbSet<PgGeideaCallBackPay> PgGeideaCallBackPays { get; set; }
        public virtual DbSet<OpOperationOrder> OpOperationOrders { get; set; }
        public virtual DbSet<OpOperationOrderProcess> OpOperationOrderProcesses { get; set; }
        public virtual DbSet<ScPriceCodeClient> ScPriceCodeClients { get; set; }
        public virtual DbSet<ScPriceCodeInventory> ScPriceCodeInventories { get; set; }
        public virtual DbSet<ScAdditionsTypeProduct> ScAdditionsTypeProducts { get; set; }
        public virtual DbSet<ScInventory> ScInventories { get; set; }
        public virtual DbSet<ScPackageNote> ScPackageNotes { get; set; }
        public virtual DbSet<ScCommandTranferInventory> ScCommandTranferInventories { get; set; }
        public virtual DbSet<ScSubDataTranferInventory> ScSubDataTranferInventories { get; set; }
        public virtual DbSet<ScProcessesDamagedStock> ScProcessesDamagedStocks { get; set; }
        public virtual DbSet<ScSubProcessesDamagedStock> ScSubProcessesDamagedStocks { get; set; }
        public virtual DbSet<ScPackage> ScPackages { get; set; }
        public virtual DbSet<ScInventoryJahez> ScInventoryJahezs { get; set; }
        public virtual DbSet<VwSalesClientBalance> VwSalesClientBalances { get; set; }
        public virtual DbSet<FnReciptVoucher> FnReciptVouchers { get; set; }
        public virtual DbSet<VwInvPackagePOS3> VwInvPackagePOS3 { get; set; }
        public virtual DbSet<ScPackagesAddon> ScPackagesAddons { get; set; }
        public virtual DbSet<ScSubInventoriesIn> ScSubInventoriesIns { get; set; }
        public virtual DbSet<ScSubInventoriesOut> ScSubInventoriesOuts { get; set; }
        public virtual DbSet<ScSubInventoryProcess> ScSubInventoryProcesses { get; set; }
        public virtual DbSet<ScSubInventoryProcessesContinue> ScSubInventoryProcessesContinues { get; set; }
        public virtual DbSet<ScSubPurchaseInvoice> ScSubPurchaseInvoices { get; set; }
        public virtual DbSet<VwSalesClientInvoice> VwSalesClientInvoices { get; set; }
        public virtual DbSet<ScGiftUsedPoint> ScGiftUsedPoints { get; set; }
        public virtual DbSet<VwInvPackagePOS3DeleteList> VwInvPackagePOS3DeleteList { get; set; }
        public virtual DbSet<VwInvPackagePOS3HideList> VwInvPackagePOS3HideList { get; set; }
        public virtual DbSet<VwUserLoyalityPoint> VwUserLoyalityPoints { get; set; }
        public virtual DbSet<ScSalesInvoice> ScSalesInvoices { get; set; }
        public virtual DbSet<ScSalesReturn> ScSalesReturns { get; set; }
        public virtual DbSet<ScSubSalesExtraFee> ScSubSalesExtraFees { get; set; }
        public virtual DbSet<ScSubSalesReturnExtraFee> ScSubSalesReturnExtraFees { get; set; }
        public virtual DbSet<MyPortalServerLink> MyPortalServerLinks { get; set; }
        public virtual DbSet<ScSalesInvoicesSummary> ScSalesInvoicesSummaries { get; set; }
        public virtual DbSet<ScPriceCode> ScPriceCodes { get; set; }
        public virtual DbSet<SnPotentialClient> SnPotentialClients { get; set; }
        public virtual DbSet<CgDevicesInfo> CgDevicesInfoes { get; set; }
        public virtual DbSet<SnMngActive> SnMngActives { get; set; }
        public virtual DbSet<ScSalesClientDataBackup> ScSalesClientDataBackups { get; set; }
        public virtual DbSet<ScPackagesBundle> ScPackagesBundles { get; set; }
        public virtual DbSet<ScSubPackagesBundle> ScSubPackagesBundles { get; set; }
        public virtual DbSet<ThirdAppInfo> ThirdAppInfoes { get; set; }
        public virtual DbSet<aaa> aaas { get; set; }
        public virtual DbSet<ScProduct> ScProducts { get; set; }
        public virtual DbSet<ScSubSalesInvoice> ScSubSalesInvoices { get; set; }
        public virtual DbSet<ScSubSalesReturn> ScSubSalesReturns { get; set; }
        public virtual DbSet<ScSubSalesReturnTax> ScSubSalesReturnTaxes { get; set; }
        public virtual DbSet<ScSubSalesTax> ScSubSalesTaxes { get; set; }
        public virtual DbSet<FnSubTaxesGroup> FnSubTaxesGroups { get; set; }
        public virtual DbSet<FnTaxesGroup> FnTaxesGroups { get; set; }
        public virtual DbSet<FnTaxesType> FnTaxesTypes { get; set; }
        public virtual DbSet<CgMngDevice> CgMngDevices { get; set; }
        public virtual DbSet<ThirdAppConfig> ThirdAppConfigs { get; set; }
        public virtual DbSet<ScClient> ScClients { get; set; }
        public virtual DbSet<MyPortalWebsiteIdentification> MyPortalWebsiteIdentifications { get; set; }
        public virtual DbSet<ScClientIdentification> ScClientIdentifications { get; set; }
        public virtual DbSet<CgMngDevicesZatca> CgMngDevicesZatcas { get; set; }
    
        public virtual int GetInvoicesByClient(Nullable<int> websiteID, Nullable<int> supplierNumber)
        {
            var websiteIDParameter = websiteID.HasValue ?
                new ObjectParameter("WebsiteID", websiteID) :
                new ObjectParameter("WebsiteID", typeof(int));
    
            var supplierNumberParameter = supplierNumber.HasValue ?
                new ObjectParameter("SupplierNumber", supplierNumber) :
                new ObjectParameter("SupplierNumber", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetInvoicesByClient", websiteIDParameter, supplierNumberParameter);
        }
    }
}
