//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SnMngActive
    {
        public int AutoID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public Nullable<int> CountUser { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ActiveCodeID { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public string ActiveCode { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> IsPaid { get; set; }
        public Nullable<bool> IsUsed { get; set; }
        public Nullable<int> WebID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public Nullable<int> BundleID { get; set; }
        public Nullable<int> CountBranch { get; set; }
        public Nullable<int> CountMobile { get; set; }
        public Nullable<int> InvoiceID { get; set; }
    }
}
