//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SnPotentialClient
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> ActivityTypeID { get; set; }
        public Nullable<int> ActivityClassID { get; set; }
        public Nullable<int> BundleID { get; set; }
        public Nullable<int> NumProductID { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public Nullable<int> NumBranches { get; set; }
        public Nullable<int> NumUsers { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<int> FollowStatusId { get; set; }
        public Nullable<int> AccountManagerId { get; set; }
        public Nullable<int> ContactPersonId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<long> WebID { get; set; }
    
        public virtual ClsCity ClsCity { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ScService ScService { get; set; }
        public virtual ScClient ScClient { get; set; }
    }
}
