//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysGroupPermission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysGroupPermission()
        {
            this.SysBrPrmsDirections = new HashSet<SysBrPrmsDirection>();
            this.SysSubHirSearchPermissions = new HashSet<SysSubHirSearchPermission>();
            this.SysSubPermissions = new HashSet<SysSubPermission>();
        }
    
        public long AutoID { get; set; }
        public int GroupID { get; set; }
        public int PageID { get; set; }
        public bool IsSubPrm { get; set; }
        public bool IsModelPrm { get; set; }
        public Nullable<int> ModelPrmID { get; set; }
        public bool CanView { get; set; }
        public Nullable<bool> CanAddNew { get; set; }
        public Nullable<bool> CanActive { get; set; }
        public Nullable<bool> CanEdit { get; set; }
        public Nullable<bool> CanDelete { get; set; }
        public Nullable<bool> CanPrint { get; set; }
        public Nullable<bool> CanSearch { get; set; }
        public Nullable<bool> CanBrowse { get; set; }
        public Nullable<bool> CanRemove { get; set; }
        public Nullable<bool> CanRestore { get; set; }
        public Nullable<bool> CanObserve { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string Details { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysBrPrmsDirection> SysBrPrmsDirections { get; set; }
        public virtual SysGroup SysGroup { get; set; }
        public virtual SysPage SysPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysSubHirSearchPermission> SysSubHirSearchPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysSubPermission> SysSubPermissions { get; set; }
    }
}
