//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysReportsFooter
    {
        public int AutoID { get; set; }
        public int DirectionID { get; set; }
        public int ReportID { get; set; }
        public string PositionName { get; set; }
        public string LevelName { get; set; }
        public string EmpName { get; set; }
        public string Code { get; set; }
        public string Details { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int SignType { get; set; }
        public Nullable<int> EmpID { get; set; }
    
        public virtual ClsDirection ClsDirection { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual SysReport SysReport { get; set; }
    }
}
