//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysReport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysReport()
        {
            this.SysReportsFooters = new HashSet<SysReportsFooter>();
            this.SysReportsPages = new HashSet<SysReportsPage>();
        }
    
        public int AutoID { get; set; }
        public string Name { get; set; }
        public string ReportLink { get; set; }
        public Nullable<int> PageID2 { get; set; }
        public string Introduction { get; set; }
        public string Conclusion { get; set; }
        public bool IsPrompt { get; set; }
        public string Code { get; set; }
        public string Details { get; set; }
        public int OrderBy { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        public virtual SysPage SysPage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysReportsFooter> SysReportsFooters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysReportsPage> SysReportsPages { get; set; }
    }
}
