//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysSMSsLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SysSMSsLog()
        {
            this.SysSMSsLogsCellNumbers = new HashSet<SysSMSsLogsCellNumber>();
            this.SysSMSsLogsEmps = new HashSet<SysSMSsLogsEmp>();
        }
    
        public long AutoID { get; set; }
        public int ProfileID { get; set; }
        public int SenderID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string ReceiverCellNumber { get; set; }
        public Nullable<int> PageID { get; set; }
        public string MsgBody { get; set; }
        public Nullable<bool> IsSent1 { get; set; }
        public string IsSentError { get; set; }
        public string Details { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsResendFailture { get; set; }
        public Nullable<int> FailtureHours { get; set; }
        public int StatusID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual SysPage SysPage { get; set; }
        public virtual SysSMSsProfile SysSMSsProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysSMSsLogsCellNumber> SysSMSsLogsCellNumbers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SysSMSsLogsEmp> SysSMSsLogsEmps { get; set; }
    }
}
