//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysTrash
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<long> ColumnID { get; set; }
        public string ColumnName { get; set; }
        public string FilePath { get; set; }
        public string Details { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual SysPage SysPage { get; set; }
    }
}
