//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemServicesHistory
    {
        public long AutoID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime ExecuteTime { get; set; }
        public int ExecuteStatus { get; set; }
        public string Details { get; set; }
        public string ErrorsDetails { get; set; }
    
        public virtual SystemService SystemService { get; set; }
    }
}
