//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThirdAppConfig
    {
        public int AutoID { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public string ClientId { get; set; }
        public string ClientSecret { get; set; }
        public string Code { get; set; }
        public string State { get; set; }
        public string Token { get; set; }
        public string AppId { get; set; }
        public Nullable<int> SubscriptionId { get; set; }
        public Nullable<int> InventoryID { get; set; }
        public Nullable<int> ThirdAppId { get; set; }
        public string Details { get; set; }
        public bool IsActive { get; set; }
        public bool IsTrash { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<int> DeviceID { get; set; }
    
        public virtual ScInventory ScInventory { get; set; }
        public virtual ThirdAppInfo ThirdAppInfo { get; set; }
    }
}
