//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TsTicket()
        {
            this.TsTicketsMsgs = new HashSet<TsTicketsMsg>();
        }
    
        public int AutoID { get; set; }
        public int EmpID { get; set; }
        public string Subject { get; set; }
        public int UserStatusID { get; set; }
        public int AdminStatusID { get; set; }
        public string BriefMsg { get; set; }
        public Nullable<int> RatingValue { get; set; }
        public bool IsTrash { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int UpdatedBy { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TsTicketsMsg> TsTicketsMsgs { get; set; }
    }
}
