//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TsTicketsMsg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TsTicketsMsg()
        {
            this.TsTicketsFiles = new HashSet<TsTicketsFile>();
        }
    
        public long AutoID { get; set; }
        public int TicketID { get; set; }
        public string Msg { get; set; }
        public string PureMsg { get; set; }
        public bool IsFromAdmin { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual TsTicket TsTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TsTicketsFile> TsTicketsFiles { get; set; }
    }
}
