//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDashBoardVehicles3_1
    {
        public string DirectionName { get; set; }
        public string SupplyType { get; set; }
        public string BrandName { get; set; }
        public int FieldsCount { get; set; }
    }
}
