//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDashBoardReports1Status
    {
        public string ReportDate { get; set; }
        public long ReportID { get; set; }
        public string ReportName { get; set; }
        public string StatusType { get; set; }
        public string DirectionName { get; set; }
    }
}
