//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwFnAccountsAmount
    {
        public int AccountID { get; set; }
        public string AccountNum { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> AccountParent { get; set; }
        public Nullable<int> AccountJournalID { get; set; }
        public int MonthID { get; set; }
        public int MonthType { get; set; }
        public int YearID { get; set; }
        public Nullable<int> YearNum { get; set; }
        public decimal PrvIns { get; set; }
        public decimal Amount { get; set; }
    }
}
