//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwInvPackagePOS3HideList
    {
        public Nullable<long> PackageID { get; set; }
        public Nullable<bool> IsPriceless { get; set; }
        public Nullable<decimal> pweight { get; set; }
        public Nullable<decimal> plength { get; set; }
        public Nullable<decimal> pheight { get; set; }
        public Nullable<decimal> pwidth { get; set; }
        public string p { get; set; }
        public string BarCode { get; set; }
        public string PkgNo { get; set; }
        public Nullable<int> invid { get; set; }
        public string i { get; set; }
        public Nullable<long> w { get; set; }
        public Nullable<bool> isnew { get; set; }
        public int prodid { get; set; }
        public Nullable<decimal> pricetax { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> pricetype { get; set; }
        public Nullable<int> imagelink { get; set; }
        public string measuremane { get; set; }
        public decimal qty { get; set; }
        public Nullable<decimal> activeprice { get; set; }
        public string pricelist { get; set; }
        public string sku { get; set; }
        public string upc { get; set; }
        public string groupcode { get; set; }
        public string guaranteeplan { get; set; }
        public Nullable<bool> issale { get; set; }
        public string pointcategory { get; set; }
        public string imageurl { get; set; }
        public decimal discount { get; set; }
        public Nullable<System.DateTime> updatedate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
    }
}
