//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwInvN16Depts
    {
        public Nullable<int> StoreSubID { get; set; }
        public Nullable<int> DeptTo { get; set; }
        public Nullable<int> DirectionID { get; set; }
        public string DeptName { get; set; }
        public int ProductID { get; set; }
        public Nullable<decimal> EstQnt { get; set; }
        public Nullable<decimal> ActQnt { get; set; }
    }
}
