//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwPackageHistory
    {
        public Nullable<long> WebsiteID { get; set; }
        public Nullable<int> WarehouseID { get; set; }
        public Nullable<long> PackageID { get; set; }
        public int InvoiceID { get; set; }
        public int RecordID { get; set; }
        public Nullable<System.DateTime> RecodeDate { get; set; }
        public Nullable<int> OperationID { get; set; }
        public Nullable<int> FromSource { get; set; }
        public Nullable<int> ToDistnation { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public int IsAdding { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsTrash { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<int> PayID { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string Statment { get; set; }
        public int IsHide { get; set; }
        public Nullable<decimal> EstimatedCost { get; set; }
        public Nullable<int> YearId { get; set; }
    }
}
