//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSalesClientBalance
    {
        public int AutoID { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> paid { get; set; }
        public Nullable<int> SupplierNumber { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public Nullable<long> WebsiteID { get; set; }
    }
}
