//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwUsersPagesSubPermission
    {
        public int UserID { get; set; }
        public long GrpPrmID { get; set; }
        public int PageID { get; set; }
        public long SubID { get; set; }
        public int TypeID { get; set; }
        public string PageCode { get; set; }
    }
}
