//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfDocsProcess
    {
        public long AutoID { get; set; }
        public int ModelID { get; set; }
        public int DocID { get; set; }
        public int EmpID { get; set; }
        public int DecisionType { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public string Details { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual WfModel WfModel { get; set; }
        public virtual WfProcess WfProcess { get; set; }
    }
}
