//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TpService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WfProcessDep
    {
        public int AutoID { get; set; }
        public Nullable<int> ProcessID { get; set; }
        public Nullable<int> DepID { get; set; }
    
        public virtual WfProcess WfProcess { get; set; }
    }
}
